### ISSUE TITLE
Micronaut Application Plugin issues with Kotlin DSL.

### ISSUE THREAD

**Issue by sureshg** [micronaut-projects/micronaut-gradle-plugin#1]
First of all thanks for the plugin, it makes things a lot simpler. I am having some issues configuring a Kotlin Micronaut app with Gradle Kotlin DSL. Not sure if it's my build script config or actual plugin issues. Here is a sample project and the issues I am facing.

 Sample App:  https://github.com/sureshg/micronaut-app/blob/master/build.gradle.kts

* Can't configure Micronaut annotation processing config in Kotlin DSL
    
<img width="419" alt="Screen Shot 2020-06-21 at 12 23 51 PM" src="https://user-images.githubusercontent.com/356994/85233619-8d0ec380-b3bc-11ea-8746-a24f2c1a1852.png">

<img width="531" alt="Screen Shot 2020-06-21 at 12 24 13 PM" src="https://user-images.githubusercontent.com/356994/85233622-9304a480-b3bc-11ea-8aeb-d0d27be8b9c2.png">

 * Server is starting, but can't access any [controller endpoints](https://github.com/sureshg/micronaut-app/blob/master/src/main/kotlin/dev/suresh/Controller.kt) (Try accessing `http://localhost:8080/1`).

* Running test from IntelliJ (`Run MicronautAppTest`) is failing with the following error
  `No tests found for given includes: [dev.xxx.MicronautAppTest](filter.includeTestsMatching)`

* Had to apply [kapt(platform(Deps.micronautBom))](https://github.com/sureshg/micronaut-app/blob/master/build.gradle.kts#L128-L130) in the build for `micronaut-data-processor` to work,  which should be taken care of by the plugin.

* Had to apply [kaptTest("io.micronaut:micronaut-inject-java")](https://github.com/sureshg/micronaut-app/blob/master/build.gradle.kts#L132), which should be taken care of by the plugin.

**Comment by graemerocher** [comment]
Here is the most basic `build.gradle.kts` that works for me:

```kotlin
plugins {
    id("org.jetbrains.kotlin.jvm") version "1.3.72"
    id("org.jetbrains.kotlin.kapt") version "1.3.72"
    id("io.micronaut.application") version "1.0.0.M5"
}

version "0.1"
group "com.example"

repositories {
    mavenCentral()
}

micronaut {
    version( "2.0.0.RC2")
    processing {
        incremental(true)
    }
}

dependencies {
    implementation("io.micronaut:micronaut-http-server-netty")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.72")
    implementation("org.jetbrains.kotlin:kotlin-reflect:1.3.72")
    implementation("io.micronaut.kotlin:micronaut-kotlin-runtime")    
    testImplementation("io.micronaut:micronaut-http-client")
    runtimeOnly("ch.qos.logback:logback-classic")
    testImplementation("io.micronaut.test:micronaut-test-junit5")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine")
}

application {
    mainClass.set("example.ApplicationKt")
}


tasks {
    test {
        useJUnitPlatform()
    }    
}

```
