### ISSUE TITLE
Cannot reference named openapi tasks in gradle file

### ISSUE THREAD

**Issue by scprek** [micronaut-projects/micronaut-gradle-plugin#1023]
Workaround, specifying the micronaut openapi tasks in a `finalizedBy` block did work

```kotlin
finalizedBy("generateClientOpenApiModels", "generateClientOpenApiApis")
```

and then 

```kotlin
    compileKotlin {
        dependsOn(copyOpenAPISpec)
    }
```

However, this has the downside of not being able to run the micronuat openapi directly without manually runinning those tasks

### Expected Behavior

We have a mono repo that has requires building the openapi docs external from gradle first, but within the same repo.

I have successfully created my tasks

```kotlin
val copyOpenAPISpec = tasks.register<Copy>("copyOpenAPISpec") {
    group = "build"
    description = "Copies the generated OpenAPI spec to the build generated directory"
    from("../openapi/output/core-api-openapi.json")
    into(layout.buildDirectory.dir(coreApiOpenApiJsonPath).get())
    dependsOn(generateCoreApiOpenAPISpec)
}
```

And have tried every combo of below (to avoid recursive dep)

```kotlin
tasks.named("generateClientOpenApiApis") {
    dependsOn(copyOpenAPISpec)
}

tasks.named("generateClientOpenApiModels") {
    dependsOn(copyOpenAPISpec)
}
```

### Actual Behaviour

Depending on which combo I tried above, neither are recognized.

```
* What went wrong:
Task with name 'generateClientOpenApiApis' not found in root project 'integration-tests'.
```

or

```
* What went wrong:
Task with name 'generateClientOpenApiModels' not found in root project 'integration-tests'.
```

However, if I try to register

```kotlin
tasks.register("generateClientOpenApiApis") {
    dependsOn(copyOpenAPISpec)
}

tasks.register("generateClientOpenApiModels") {
    dependsOn(copyOpenAPISpec)
}
```

Gradle complains they exist

```
* What went wrong:
Cannot add task 'generateClientOpenApiApis' as a task with that name already exists.
```

### Steps To Reproduce

1. Try to access the openapi tasks by name to add dependnecies or whatever else

### Environment Information

micronautGradlePlugin=4.4.2

### Version

4.5.1

**Comment by altro3** [comment]
Need full example for it. Can't reproduce it correctly

**Comment by altro3** [comment]
@scprek ping

**Comment by scprek** [comment]
I will, I just need some time. Will do next week.

**Comment by scprek** [comment]
https://github.com/scprek/demo

https://github.com/scprek/demo/actions/runs/10562328414/job/29260049558

**Comment by altro3** [comment]
@scprek As I told you, all works fine, but in your example you use wrong task names. Look to this screenshot and you will see right task names:

<img width="889" alt="{53CD444B-17A9-4070-B3DA-919A9230478A}" src="https://github.com/user-attachments/assets/a596ca88-562c-43e0-95d1-c59314d2dba8">
