### ISSUE TITLE
Add multi-language documentation with Gradle Kotlin DSL examples

### ISSUE THREAD

**Issue by LtTempletonPeck** [micronaut-projects/micronaut-gradle-plugin#113]
The current documentation only provides Gradle Groovy `gradle.build` examples and not Gradle Kotlin DSL `gradle.build.kts` examples e.g.

```gradle
nativeImage {
    args('--static')
}
```

In Gradle Kotlin script is
```kotlin
tasks.named<io.micronaut.gradle.graalvm.NativeImageTask>("nativeImage") {
    args("--static")
}
```

Kotlin users prefer to use Kotlin all the way down and not having the examples adds friction to adopting the plugin.

I don't think the Micronaut Gradle Plugin documentation is published using adoc, it only has a README in markdown. So its not possible to use test source snippets for multi-language docs like [this](https://github.com/micronaut-projects/micronaut-core/issues/1265)

If you are happy for them to appear after the Groovy examples in the README I'll start a PR to add these?

**Comment by graemerocher** [comment]
PRs welcome, though I think it ca be written simpler with in Kotlin :

```
tasks {
      nativeImage {
          args("--static")
      } 
}
```

**Comment by LtTempletonPeck** [comment]
Damn I missed that! That's even easier but proves the point that a few examples would help :smile:

**Comment by graemerocher** [comment]
yeah although I think the above syntax works in both Groovy and Kotlin so it could be just a matter of updating the docs to make sure a compatible syntax supported by both is used
