### ISSUE TITLE
Resources generated from other sources are not included in the native image

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-gradle-plugin#114]
The Management GraalVM test application uses a gradle plugin that generates a `git.properties` file that then is exposed automatically by Micronaut `/info` endpoint.

When running the app on the JVM you can send a `curl localhost:8080/info` request and you get that information.
To make this work in a native-image I have the following `resource-config.json` in the `src/main/resources/META-INF/native-image/.....` directory:

```
{
  "resources": [
    {"pattern":"\\Qgit.properties\\E"}
  ]
}
```

This has been working for a long time.

Now I've switched the application to use the Gradle plugin and the curl request returns an empty response because the `git.properties` file seems not to be included in the final native-image.

To reproduce the issue:

- `git clone https://github.com/micronaut-graal-tests/micronaut-management-graal`
- `cd micronaut-management-graal`
- `git checkout issue-plugin-resources`
- `sdk use java 21.0.0.r8-grl`
- `./gradlew nativeImage`
- Start the native image
- `curl localhost:8080/info` returns an empty response.

**Comment by ilopmar** [comment]
I've tried a locally built snapshot with the change and it still doesn't work for me. You have done the changes in MicronautDockerPlugin but maybe you need to do the same in MicronautGraalPlugin?

**Comment by graemerocher** [comment]
Good catch

**Comment by ilopmar** [comment]
Yeah, it works now! :100:
