### ISSUE TITLE
`-parameters` compiler option is not included for Java projects

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-gradle-plugin#152]
Before having this plugin we included the `-paremeters` flag for the `JavaCompile` tasks in `build.gradle`:

```groovy
tasks.withType(JavaCompile) {
    options.compilerArgs.addAll([
        '-parameters',
        // enables incremental compilation
		...
    ])
}
```

Now it seems it is only included for [Kotlin](https://github.com/micronaut-projects/micronaut-gradle-plugin/blob/1cef660aa25c71c17b3147587808c90351b54d69/src/main/java/io/micronaut/gradle/MicronautKotlinSupport.java#L176) and [Groovy](https://github.com/micronaut-projects/micronaut-gradle-plugin/blob/385e7c8eb9bd5529a3940ca8374407c8e74e7c2e/src/main/java/io/micronaut/gradle/MicronautLibraryPlugin.java#L308) but not for Java apps.

**Comment by graemerocher** [comment]
This is pretty serious and should be fixed before 2.4
