### ISSUE TITLE
Regression setting the name of the native-image executable with 1.4.1

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-gradle-plugin#157]
After fixing #128 now the plugin doesn't respect the name of the native image executable defined as

```groovy
nativeImage {
    imageName("basic-app")
}
```

The native image is created as `application` instead of `basic-app`

## Reproduce the issue:

- `mn create-app foo`
- `cd foo`
- `echo "nativeImage { imageName('basic-app') }" >> build.gradle`
- Set plugin version to 1.4.0: `sed -i "s/1.3.4/1.4.0/g" build.gradle`
- Use GraalVM
- `./gradlew nativeImage`. Verify that the native image created is `basic-app`. Abort the generation
- Change the gradle plugin version to 1.4.1: `sed -i "s/1.4.0/1.4.1/g" build.gradle`
- `./gradlew nativeImage`. Now the native image is created as `application`

## Output

```
$ mn create-app foo
| Application created at /tmp/foo

$ cd foo
$ echo "nativeImage { imageName('basic-app') }" >> build.gradle
$ sed -i "s/1.3.4/1.4.0/g" build.gradle
$ sdk use java 21.0.0.2.r8-grl         
$ ./gradlew nativeImage
> Task :compileJava
> Task :processResources
> Task :classes

> Task :nativeImage
[basic-app:66510]    classlist:   1,766.06 ms,  1.39 GB <---- basic-app
[basic-app:66510]        (cap):     438.66 ms,  1.63 GB
[basic-app:66510]        setup:   1,671.99 ms,  1.63 GB
<=========----> 75% EXECUTING [4s]
> :nativeImage
^C

$ sed -i "s/1.4.0/1.4.1/g" build.gradle                                                                                            
$ ./gradlew nativeImage
> Task :compileJava
> Task :processResources UP-TO-DATE
> Task :classes

> Task :nativeImage
[application:66833]    classlist:   1,876.95 ms,  1.30 GB <---- wrong name
<=========----> 75% EXECUTING [3s]
> :nativeImage
```

**Comment by graemerocher** [comment]
Great 🙄
