### ISSUE TITLE
Micronaut gradle build creates "layers" dir outside project.buildDir

### ISSUE THREAD

**Issue by l0co** [micronaut-projects/micronaut-gradle-plugin#165]
Please refer [KT-45301](https://youtrack.jetbrains.com/issue/KT-45301). They've probably fixed the bug with "kotlin" dir, but there's still "layers" dir created by Micronaut, and it's outside `project.buildDir`. The example project is attached in kotlin ticket.

**Comment by graemerocher** [comment]
can't reproduce this personally

**Comment by l0co** [comment]
Can't you reproduce from the example project attached to kotlin ticket?

**Comment by graemerocher** [comment]
There doesn't appear to be an example attached, only a bunch of comments
