### ISSUE TITLE
Serverless Application with features aws-lambda, graalvm, aws-custom-runtime sets incorrect main class

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-gradle-plugin#171]
Related to: https://github.com/micronaut-projects/micronaut-gradle-plugin/issues/132 and https://github.com/micronaut-projects/micronaut-starter/issues/722

## Steps to reproduce

- Generate a serverless function with features `aws-lambda` `graalvm` `aws-custom-runtime`.
- Set as runtime "lambda". You need this otherwise you will not have a `buildNativeLambda` gradle task. 

```groovy
micronaut {
   runtime("lambda")
  ...
}

application {
    mainClass.set("com.example.BookLambdaRuntime") // Micronaut Launch generates this main class
} 
```
- Execute `./gradlew buildNativeLambda` you will see in the output:

```
...
main -H:Class=io.micronaut.function.aws.runtime.MicronautLambdaRuntime -H:Name=application
```
where the main class is set to `io.micronaut.function.aws.runtime.MicronautLambdaRuntime` which is the correct main class for Applications not for serverless functions. 

It should say: 

```
/main -H:Class=com.example.BookLambdaRuntime -H:Name=application --no-fallback -cp /home/app/libs/*.jar:/home/app/resources:/home/app/application.jar
```

A workaround is to use the native extension to explicitly define the main class used for GraalVM Native image. 

```groovy
application {
    mainClass.set("com.example.BookLambdaRuntime")
}
nativeImage {
    main("com.example.BookLambdaRuntime")
}
```

**Comment by ilopmar** [comment]
I'm not really sure how we can fix this. In #132 what I did was setting the main class of the nativeImage task to `io.micronaut.function.aws.runtime.MicronautLambdaRuntime` in case the runtime is Lambda: https://github.com/micronaut-projects/micronaut-gradle-plugin/blob/master/src/main/java/io/micronaut/gradle/graalvm/MicronautGraalPlugin.java#L74-L76

But as we've seen the problem with that approach is that it works for Apps but breaks the Function Apps.

We set the native-image `-H:Class` here https://github.com/micronaut-projects/micronaut-gradle-plugin/blob/master/src/main/java/io/micronaut/gradle/graalvm/NativeImageTask.java#L132 but that is the class we previously defined. 

Unless we have a way to differentiate a normal application from a function app I don't see how we can set the right class for both cases. 
One approach could be using the `micronaut-cli.yml` file but that seems hacky, ugly and probably won't work properly in multi-project builds.

Another option could be setting the following in Starter for Funtion Apps:

```groovy
nativeImage {
    main("com.example.BookLambdaRuntime")
}
```

Any thoughts?

**Comment by ilopmar** [comment]
I have the following working to know if there is an application or a function and only in the case of the application and lambda runtime I change the main class:


```java
MicronautRuntime mr = MicronautApplicationPlugin.resolveRuntime(project);

DependencySet implementation = project.getConfigurations().getByName("implementation").getDependencies();
boolean isAwsFunctionApp = implementation.stream()
		.anyMatch(dependency -> Objects.equals(dependency.getGroup(), "io.micronaut.aws") && dependency.getName().equals("micronaut-function-aws"));

if (mr == MicronautRuntime.LAMBDA && !isAwsFunctionApp) {
	nativeImageTask.setMain("io.micronaut.function.aws.runtime.MicronautLambdaRuntime");
}
```

@graemerocher what do you think about this approach? If it makes sense I'll add a few tests and send a PR.

**Comment by graemerocher** [comment]
Can we not simply check if the user specifies a main class and set it only if it is not already set?

**Comment by ilopmar** [comment]
The user always specifies a main class because Starter generates it:

```groovy
// For a Function
application {
    mainClass.set("example.micronaut.BookLambdaRuntime")
}

// For an application
application {
    mainClass.set("example.micronaut.Application")
}
```

The problem is that after #132 the main class is changed to `io.micronaut.function.aws.runtime.MicronautLambdaRuntime` when generating the native image for Lambda. That works for apps but not for function that still need `example.micronaut.BookLambdaRuntime` as the main class.
