### ISSUE TITLE
Micronaut plugin failed to detect GraalVM JDK

### ISSUE THREAD

**Issue by sergey-morenets** [micronaut-projects/micronaut-gradle-plugin#181]
Hi

We use Gradle Docker image where we added and installed GraalVM using SDKMan.
However if we try to build native image:

`gradle --no-daemon -Dorg.gradle.java.home=/root/.sdkman/candidates/java/21.0.0.2.r11-grl clean nativeImage`

we always receive an error:

`A GraalVM SDK is required to build native images`

We looked into the sources and seems that GraalUtil uses **java.vendor.version** property to detect GraalVM SDK. Basically it just checks if this property contains "graal" text (in any registry). 
If we run this code in jshell it returns correct text:

```
jshell> System.getProperty("java.vendor.version")
$1 ==> "GraalVM CE 21.0.0.2"
```

So to avoid this issue we had to explicitly specify "graal":
`gradle --no-daemon -Dorg.gradle.java.home=/root/.sdkman/candidates/java/21.0.0.2.r11-grl -Djava.vendor.version=graal clean nativeImage`

Please, advise why build failed without explicit system property.

**Comment by graemerocher** [comment]
I was not aware of `org.gradle.java.home`

Currently the plugin will look for `JAVA_HOME` or `GRAALVM_HOME` variables

**Comment by melix** [comment]
Once #228 is merged, the plugin will rely on the official GraalVM plugin to detect installations. It will use Gradle's [toolchain support](https://docs.gradle.org/7.2/userguide/toolchains.html) and will therefore look for installations in places like SDKMAN!. In addition it will also support looking at the `GRAALVM_HOME` directory.
