### ISSUE TITLE
Micronaut doesn't provide error details and ways to resolve it

### ISSUE THREAD

**Issue by sergey-morenets** [micronaut-projects/micronaut-gradle-plugin#182]
Hi

We use Gradle Docker image where we added and installed GraalVM using SDKMan.
However if we try to build native image:

`gradle --no-daemon -Dorg.gradle.java.home=/root/.sdkman/candidates/java/21.0.0.2.r11-grl -Djava.vendor.version=graal clean nativeImage`
we always receive an error:

`A problem occurred starting process 'command 'native-image'`

Even if we add _--info_ or _--debug_ arguments no additional information is printed. However it turned out that Micronaut plugin requires **GRAALVM_HOME** environment variable:

`ARG GRAALVM_HOME=/root/.sdkman/candidates/java/21.0.0.2.r11-grl`

Please, add this information to the documentation section and error message.

**Comment by melix** [comment]
Once #228 is merged, we're going to use the official GraalVM plugin which provides better error messages in this context.
