### ISSUE TITLE
`run --continuous` parameter `micronaut.io.watch.paths` uses hardcoded `"src/main"` srcDir

### ISSUE THREAD

**Issue by garkin** [micronaut-projects/micronaut-gradle-plugin#198]
`"src/main"` is hardcoded, and not deducted.
https://github.com/micronaut-projects/micronaut-gradle-plugin/blob/c2d3b74389783d792cbc3d5885ccffa3b0fe5936/src/main/java/io/micronaut/gradle/MicronautApplicationPlugin.java#L127
But 11 lines below it's deducted using API. 
https://github.com/micronaut-projects/micronaut-gradle-plugin/blob/c2d3b74389783d792cbc3d5885ccffa3b0fe5936/src/main/java/io/micronaut/gradle/MicronautApplicationPlugin.java#L138

**Comment by graemerocher** [comment]
Good analysis, would you like to send a PR?

**Comment by garkin** [comment]
Not sure about should i explicitly ping PR here or not, but just in case its #199

**Comment by ilopmar** [comment]
Closed by #199
