### ISSUE TITLE
dockerBuildNative task does not bundle resources

### ISSUE THREAD

**Issue by charlie-harvey** [micronaut-projects/micronaut-gradle-plugin#204]
`dockerBuildNative` task in the `micronaut-gradle-plugin` is not bundling my resources (*.yml files, logback.xml).

I see all the steps in the `DockerfileNative` and it should be working. But its not. Nothing is ever set. Not my port, not database connections. Nothing. I have files in `build/layers/resources`. They match the files in `src/main/resources`.

`nativeImage` works just fine. When I run `nativeImage` and then `./build/native-image/application` my app starts up great, clearly the resources are in place.

But the `dockerBuildNative` is just not working.

**Comment by ilopmar** [comment]
I'm not able to reproduce this issue. This is the test application I've created https://github.com/micronaut-core-issues-test-app/gradle-plugin-issue204.

I have a `ServerStartupEvent` listener that prints the content of a variable defined in `application.yml` when the app starts up: https://github.com/micronaut-core-issues-test-app/gradle-plugin-issue204/blob/master/src/main/java/gradle/plugin/issue204/MyBean.java

I have two different messages, one in [application.yml](https://github.com/micronaut-core-issues-test-app/gradle-plugin-issue204/blob/master/src/main/resources/application.yml#L5) and another one in [application-dev.yml](https://github.com/micronaut-core-issues-test-app/gradle-plugin-issue204/blob/master/src/main/resources/application-dev.yml#L1)



**1.-** I create the native image with `./gradlew nativeImage` and run it. Without any additional parameters the app shows the message from `application.yml`:

```
$ build/native-image/application    
 __  __ _                                  _   
|  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_ 
| |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
| |  | | | (__| | | (_) | | | | (_| | |_| | |_ 
|_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
  Micronaut (v2.5.4)

-------> someText = from application.yml
11:54:29.491 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 80ms. Server Running: http://localhost:8080
11:54:31.292 [Thread-1] INFO  io.micronaut.runtime.Micronaut - Embedded Application shutting down
```

**2.-** Changing the environment to `dev` the app shows the message from `application-dev.yml`. Which is the expected result:

```
ivan@doraemon:~/workspaces/micronaut-apps/gradle-plugin-issue204$ MICRONAUT_ENVIRONMENTS=dev build/native-image/application
 __  __ _                                  _   
|  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_ 
| |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
| |  | | | (__| | | (_) | | | | (_| | |_| | |_ 
|_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
  Micronaut (v2.5.4)

11:54:47.799 [main] INFO  i.m.context.env.DefaultEnvironment - Established active environments: [dev]
-------> someText = from application-dev.yml
11:54:47.847 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 57ms. Server Running: http://localhost:8080
11:54:50.563 [Thread-1] INFO  io.micronaut.runtime.Micronaut - Embedded Application shutting down
```

**3.-** Now I create the native image using docker running `./gradlew dockerBuildNative` and start the container. As before the message from `application.yml` is displayed:

```
$ docker run -it --rm gradle-plugin-issue204 
 __  __ _                                  _   
|  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_ 
| |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
| |  | | | (__| | | (_) | | | | (_| | |_| | |_ 
|_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
  Micronaut (v2.5.4)

-------> someText = from application.yml
09:57:02.383 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 66ms. Server Running: http://c80fc202091d:8080
09:57:03.837 [Thread-1] INFO  io.micronaut.runtime.Micronaut - Embedded Application shutting down
```

**4.-** Now passing the `dev` environment as parameter it shows the message from `application-dev.yml`, which means that the `src/main/resources` files are included in the native image.

```
$ docker run -it --rm -e MICRONAUT_ENVIRONMENTS=dev gradle-plugin-issue204
 __  __ _                                  _   
|  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_ 
| |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
| |  | | | (__| | | (_) | | | | (_| | |_| | |_ 
|_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
  Micronaut (v2.5.4)

09:57:09.529 [main] INFO  i.m.context.env.DefaultEnvironment - Established active environments: [dev]
-------> someText = from application-dev.yml
09:57:09.607 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 82ms. Server Running: http://b1d020dd5180:8080
09:57:43.540 [Thread-1] INFO  io.micronaut.runtime.Micronaut - Embedded Application shutting down
```

If you have a reproducer, please share it with us or submit a PR to my sample app that shows the problem.

**Comment by ilopmar** [comment]
Another thing I've tried is create a multi-project build. Basically moving the application to a directory and defining a `settings.gradle` file in the parent directory. It also works as expected.

**Comment by charlie-harvey** [comment]
Thank you for taking the time and investigating. Pretty sure you are right. There is something I am doing wrong with my setup where the classpath is wrong and properties are not loading. It must be something else though because this looks good. I will try to replicate my setup with a clean repo and hopefully I'll nail it down. If I find something I will open a different Issue. This one can be closed.

Thanks!
