### ISSUE TITLE
Injection-only runtime

### ISSUE THREAD

**Issue by msgilligan** [micronaut-projects/micronaut-gradle-plugin#238]
It would be nice if the Micronaut Gradle Plugin (and maybe the Maven plugin, too) supported a `runtime` option that only depended on `micronaut-inject`. This would allow for extremely lightweight command-line applications and a starting point for things like JavaFX applications that use Micronaut DI, but don't need the full runtime, networking, etc.

This might be configured as follows:

```
micronaut {
    version = "3.0.0"
    runtime "inject_only"
}
```

I also added a commented on related Issue https://github.com/micronaut-projects/micronaut-gradle-plugin/issues/110#issuecomment-903181651

**Comment by melix** [comment]
Unless I'm mistaken, if you do this:

```
plugins {
    id 'io.micronaut.minimal.application' version '3.2.2'
}

repositories {
    mavenCentral()
}

micronaut {
    version = "3.3.3"
    runtime "none"
}
```

you get exactly what you're looking for: it would apply the `micronaut-inject` dependency, as well as the BOM: https://scans.gradle.com/s/maay6to2lxkkg/dependencies?toggled=W1swXSxbMCwwXV0

**Comment by msgilligan** [comment]
Thanks, @melix - that did the trick!  (See https://github.com/SupernautApp/supernaut-fx-sample-gradle/pull/3)

I took a quick look at the documentation and I don't see a mention of the `"none"` runtime...
