### ISSUE TITLE
dockerNativeBuild does not include resource-config.json

### ISSUE THREAD

**Issue by DmitryKubahov** [micronaut-projects/micronaut-gradle-plugin#243]
### Expected Behavior

While executing task **dockerBuildNative** result **DockerfileNative** should contain additional action for copying **resource-config.json** and setting correct **-H:ConfigurationFileDirectories** attribute to the **native-image** command

### Actual Behaviour

After execution **dockerBuildNative** result **DockerfileNative** contains only copy operations for:
- libs
- resources
- application.jar
And **native-image** command contains wrong value of attribute "-H:ConfigurationFileDirectories" - absolute path to **host** resource-config folder (...**build/generated/resources/graalvm**). But this is host path, not a docker one.

May be the root cause of [#239]

### Steps To Reproduce

Create simple micronaut application and just run: ./gradlew clean generateResourceConfigFile dockerBuildNative

### Environment Information

- MacOS
- GraalVM 21.2.0

### Version

3.0.0

**Comment by graemerocher** [comment]
@melix could you take a look?

**Comment by melix** [comment]
This is actually already fixed on the branch which uses the official GraalVM plugin. Depending on when this release goes out we might consider a hotfix.
