### ISSUE TITLE
Dockerfile in the project root directory not used

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-gradle-plugin#25]
If the user has its own `Dockerfile` in the project root, that file is not used when building the app:

```
$ ./gradlew dockerBuild
...

> Task :dockerBuild
Building image using context '/home/ivan/workspaces/micronaut-graal-tests/micronaut-basic-app'.
Using Dockerfile '/home/ivan/workspaces/micronaut-graal-tests/micronaut-basic-app/build/docker/Dockerfile'
...
```

The file `build/docker/Dockerfile` is used instead of the one in the project root directory.

Note the same applies when running `dockerBuildNative`, although in this case I'm not really sure. I mean, if the user wants to use their own dockerfile and put it in the project root directory, they should run the task `dockerBuild` and once this bug is fixed, the right file will be used. 
```
$ ./gradlew dockerBuildNative
...

> Task :dockerBuildNative
Building image using context '/home/ivan/workspaces/micronaut-graal-tests/micronaut-basic-app'.
Using Dockerfile '/home/ivan/workspaces/micronaut-graal-tests/micronaut-basic-app/build/docker/DockerfileNative'
```

**Comment by graemerocher** [comment]
I can't reproduce this personally

**Comment by ilopmar** [comment]
Steps to reproduce the issue:

- `git clone https://github.com/micronaut-graal-tests/micronaut-basic-app`
- `cd micronaut-basic-app`
- `git checkout micronaut-gradle-plugin`
- There is no `Dockerfile` in the project root directory.
- `./gradlew dockerfile`
- `cp build/docker/Dockerfile .`
- `./gradlew dockerBuild`

```
> Task :dockerfile

> Task :dockerBuild
Building image using context '/tmp/micronaut-basic-app'.
Using Dockerfile '/tmp/micronaut-basic-app/build/docker/Dockerfile' <-------------
Using images 'basic-app'.
Step 1/7 : FROM openjdk:14-alpine
 ---> 8273876b08aa
...
```

You can see that the build is using `/tmp/micronaut-basic-app/build/docker/Dockerfile` instead of `/tmp/micronaut-basic-app/Dockerfile`

**Comment by graemerocher** [comment]
This seems to be erroneous output coming from the Docker gradle plugin. If you add:

```
RUN echo "BUILDING WITH DOCKER!!!"
```

To the Dockerfile it prints, so the correct Dockerfile is being used.
