### ISSUE TITLE
Documentation update for layered section

### ISSUE THREAD

**Issue by sergey-morenets** [micronaut-projects/micronaut-gradle-plugin#266]
### Expected Behavior

The documentation states:

`The plugin creates a "layered" application in build/layers and from that directory you can run java -jar myapp.jar. It works because that directory contains a lib directory with all the libraries and a resources directory with the configuration. Keep in mind that copying the only .jar file to another directory won't work.`

So I assume from this block that layers should be located in the build/layers folder.

### Actual Behaviour

Since Micronaut 3 they're located in the **build/docker/layers** folder.

### Steps To Reproduce

Run gradle build command for any Micronaut 3 project.

### Version

3.0.3

**Comment by frehov** [comment]
The offending code seems to be located here at least - https://github.com/micronaut-projects/micronaut-gradle-plugin/blob/a499581cb81c4c059644e6ca81cc0c06bbe74f0b/src/main/java/io/micronaut/gradle/docker/tasks/BuildLayersTask.java#L29
and it was updated by #179 but no documentation update was added.

**Comment by frehov** [comment]
This seems to have "broken" more with the 3.1 plugin update, and at least on my machine, it now adds the sourceSet path as well, so you get `docker/main/layers`, assuming you only have a single sourceSet called main.

**Comment by sergey-morenets** [comment]
> This seems to have "broken" more with the 3.1 plugin update, and at least on my machine, it now adds the sourceSet path as well, so you get `docker/main/layers`, assuming you only have a single sourceSet called main.

@frehov Yes, you're right. And plugin documentation is not updated yet.
