### ISSUE TITLE
Upgrade to Kotlin 1.4.0

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-gradle-plugin#27]
During the Micronaut 2.0 upgrade in the remaining modules, we are also upgrading to Kotlin 1.4.0. It will also be (or should be) included in Micronaut 2.1, so I think it makes sense to upgrade the dependencies in this plugin to Kotlin 1.4.0 as it will be included in Micronaut 2.1.

**Comment by graemerocher** [comment]
There are no direct dependencies on Kotlin in the plugin, they are `compileOnly` but yes from a testing perspective it makes sense
