### ISSUE TITLE
Filename of native executable should match project name

### ISSUE THREAD

**Issue by aalmiray** [micronaut-projects/micronaut-gradle-plugin#270]
### Feature description

A project configured with the micronaut-maven-plugin (`3.1.0`) produces an executable whose filename matches `${project.artifactId}` by default (good!). However a project configured with the micronaut-gradle-plugin (`2.0.6`) produces an executable whose name is "application".

It's unclear to me if this setting is coming from the Micronaut plugin or is a default setting of the GraalVM gradle plugin.

**Comment by melix** [comment]
This is from the Micronaut Gradle plugin. The GraalVM plugin uses the project name, so it means that the next release (3.0.0) will fix this. It's already on master.
