### ISSUE TITLE
Gradle continuous reloading not working in MN 3.1.1 when using Groovy language

### ISSUE THREAD

**Issue by luiszimmermann** [micronaut-projects/micronaut-gradle-plugin#292]
### Expected Behavior

App should reload/restart when changes are detected in the source files when running with the `-t` argument.

### Actual Behaviour

Nothing happens.

### Steps To Reproduce

1. Create a new app with mn: `mn create-app com.reloadtest -l=groovy`
2. Run the app using gradle: `./gradlew run -t`
3. Change some file like `Application.groovy`
4. See in the terminal that nothing changes and the app doesn't reload.

### Environment Information

```
Linux 5.11.0-38-generic micronaut-projects/micronaut-core#42~20.04.1-Ubuntu SMP Tue Sep 28 20:41:07 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
```
openjdk version "1.8.0_302"
OpenJDK Runtime Environment Corretto-8.302.08.1 (build 1.8.0_302-b08)
OpenJDK 64-Bit Server VM Corretto-8.302.08.1 (build 25.302-b08, mixed mode)
```
```
Micronaut Version: 3.1.1
```

### Example Application

https://launch.micronaut.io/demo.zip?lang=groovy

### Version

3.1.1

**Comment by jameskleeh** [comment]
The issue here is that the watch paths do not include src/main/groovy

```
    static void main(String[] args) {
        println(System.getProperty("micronaut.io.watch.restart"))
        println(System.getProperty("micronaut.io.watch.enabled"))
        println(System.getProperty("micronaut.io.watch.paths"))
```

results in 

```
true
true
/Users/jameskleeh/IdeaProjects/sample-projects/reloadtest/src/main/resources,/Users/jameskleeh/IdeaProjects/sample-projects/reloadtest/src/main/java
```

Note that if I copy the code and put it at the end of the `build.gradle` locally in the project, it contains `src/main/groovy`.

```
def sourceSet = project.getConvention()
        .getPlugin(JavaPluginConvention.class)
        .getSourceSets().findByName("main")

System.out.println(sourceSet
        .getAllSource()
        .getSrcDirs()
        .stream()
        .map(File::getPath)
        .collect(Collectors.joining(",")));
```

**Comment by melix** [comment]
There's probably a race condition in the Gradle plugin, where the system property is computed too early. From the code I suspect this can happen if the `groovy` plugin is applied _after_ the `application` (or micronaut application) plugin.
