### ISSUE TITLE
Test framework configuration fails with Gradle 7.3

### ISSUE THREAD

**Issue by melix** [micronaut-projects/micronaut-gradle-plugin#296]
### Expected Behavior

A project generated from Launch should work out of the box using Gradle 7.3.

### Actual Behaviour

Running the build fails with:

A problem occurred configuring root project 'demo'.
> The value for task ':test' property 'testFrameworkProperty' is final and cannot be changed any further.

The stack trace leads to another ordering issue in the Gradle plugin:

```
        at io.micronaut.gradle.MicronautLibraryPlugin.lambda$apply$4(MicronautLibraryPlugin.java:101)
        at org.gradle.configuration.internal.DefaultUserCodeApplicationContext$CurrentApplication$1.execute(DefaultUserCodeApplicationContext.java:123)
        at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingAction$1.run(DefaultListenerBuildOperationDecorator.java:152)

```

### Steps To Reproduce

Create a Gradle project using Micronaut Launch, don't specify any testing framework.
Run the build with Gradle 7.3-rc-3, see it fail.

Workaround is to add:

```
tasks.withType(Test).configureEach {
	useJUnitPlatform()
}
```

to the build file.

### Version

3.1.3

**Comment by hantsy** [comment]
Got the same error when upgrading to Gradle 7.3. 

```bash 
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'demo'.
> The value for task ':test' property 'testFrameworkProperty' is final and cannot be changed any further.
```

**Comment by wetted** [comment]
Also seeing the same problem. We're using Micronaut 2.5.12 and the plugin 1.5.4 on AdoptOpenJDK 8, and get the same failure trying to upgrade to Gradle 7.3. I also get the same problem creating Micronaut 2 or 3 apps in Launch and upgrading them to Gradle 7.3. 

On our projects we're using the Gradle 7 version catalog feature across all our projects, so it's in our best interest to track these Gradle upgrades, but this issue is a blocker for that. I will try the workaround noted above.

This is the error I get upgrading a default Launch project (3.1.3, JDK8, JUnit5):
```
% ./gradlew wrapper --gradle-version=7.3
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'gradle73FailWithMn3'.
> The value for task ':test' property 'testFrameworkProperty' is final and cannot be changed any further.
```

**Comment by codepitbull** [comment]
We ran into the same issue.
Looks like gradle did something I NEVER expected to happen for a patch release: They changed behavior:

https://githubmemory.com/repo/gradle/gradle/issues/18606

**Comment by tresat** [comment]
This is going to be changed on the Gradle side.  See: https://github.com/gradle/gradle/issues/19058

**Comment by melix** [comment]
I understand that Gradle is going to revert the change, but I'm not sure how we can prepare for the change in 8.0. Basically, we have this code:

https://github.com/micronaut-projects/micronaut-gradle-plugin/blob/a8161decae12dda87618b5c1a4c4bc560b805865/src/main/java/io/micronaut/gradle/MicronautLibraryPlugin.java#L99-L106

which is executed in an `afterEvaluate`. The idea is to say "if the user didn't configure a specific test framework, use JUnit Platform". It has to be executed in an `afterEvaluate` because we don't know when the user is "done" with configuration. I also understand that this is basically broken because if the user configures test options, then they would be ignored when this is called.

An option would be to configure `useJUnitPlatform()`, but if the test framework is set, _change it_.
