### ISSUE TITLE
Non existent test resource directory fails `nativeTest`

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-gradle-plugin#306]
### Expected Behavior

Having no `src/test/resources` directory should not fail the build

### Actual Behaviour

```
> Task :generateTestResourcesConfigFile FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateTestResourcesConfigFile'.
> java.nio.file.NoSuchFileException: /Users/graemerocher/dev/micronaut/apps/quick-test/build/resources/test
```

### Steps To Reproduce

Create a new micronaut project with gradle plugin 3.0.0-M1 and run `gradle nativeTest`

### Environment Information

- Gradle Plugin 3.0.0-M1

### Version

Any

**Comment by graemerocher** [comment]
@melix can you bump the priority on this one, run into it quite frequently

**Comment by graemerocher** [comment]
Note that the description is incorrect, you have to have at least 1 file in `src/test/resources` otherwise it fails as well

**Comment by melix** [comment]
See https://github.com/graalvm/native-build-tools/issues/175
