### ISSUE TITLE
Support build both war and fatjar without modify `build.gradle` like Spring Boot or Grails ?

### ISSUE THREAD

**Issue by abcfy2** [micronaut-projects/micronaut-gradle-plugin#318]
### Feature description

Spring Boot or Grails can build fatjar or war in one time without change `build.gradle`.

Would you please support this feature like Spring Boot or Grails ?

Thanks.

**Comment by ilopmar** [comment]
You can apply the `war` plugin and then, when building you app, you'll have a runnable fatjar and a war file:

![image](https://user-images.githubusercontent.com/559192/143548374-452e4645-0e02-4975-96ce-71eacbc23462.png)

**Comment by abcfy2** [comment]
Thank you.
