### ISSUE TITLE
Support custom (additional) sourceSets via provided Gradle API

### ISSUE THREAD

**Issue by soberich** [micronaut-projects/micronaut-gradle-plugin#35]
Hi,

Instead of literally expecting "main" or some other sourceSet name and adding dependencies to that, it's better to use Gradle's `SourceSet#getImplementationConfigurationName()` and others.

```kotlin
dependencies {
    sourceSets.configureEach {
        if ("test" !in name && "Test" !in name) {
            implementationConfigurationName(enforcedPlatform(kotlin("bom")))
            implementationConfigurationName("org.jetbrains.kotlinx:atomicfu:0.14.4")
            implementationConfigurationName("org.jetbrains.kotlinx:kotlinx-collections-immutable-jvm:0.3.2")
            implementationConfigurationName("org.jetbrains.kotlinx:kotlinx-io-jvm:0.2.0")
        }
    }
}
```

https://github.com/gradle/gradle/blob/master/subprojects/plugins/src/main/java/org/gradle/api/tasks/SourceSet.java

same goes for tasks names

Otherwise plugin fails to add deps to appropriate sourceSets and always adds them to "main".

**Comment by graemerocher** [comment]
We would probably need to make the configurations configurable since it is IMO since we cannot assume to configure all of them.
