### ISSUE TITLE
Task dockerBuildNative produces wrong path in DockerfileNative when it is executed under Windows

### ISSUE THREAD

**Issue by hci2** [micronaut-projects/micronaut-gradle-plugin#358]
### Expected Behavior

Executing micronaut gradle plugin task `dockerBuildNative` should create a native compiled docker image.

This is working under WSL2 Ubuntu but not in Windows. See details below:

Command: gradle :app:dockerBuildNative

![image](https://user-images.githubusercontent.com/19223435/147946630-9967c7ad-eafd-4d35-9a90-6fcbb473f7f7.png)

### Actual Behaviour

It stops in Step RUN native-image because there is a path issue to the referenced \home\app\application.jar instead of /home/app/application.jar. It seems that the produced DockerfileNative has path issues.

This happens when running the same command under CMD in the Windows terminal. See details below:

Command: gradle :app:dockerBuildNative

![image](https://user-images.githubusercontent.com/19223435/147947540-d64875c6-7dde-447e-8e91-09950a5001f9.png)

### Steps To Reproduce

1. Open CMD
2. gradle/gradlew :<application>:dockerBuildNative

### Environment Information

- Windows 10 (Windows 10 Pro, 21H1, 19043.1415)
- Gradle/Gradlew 7.2
- openjdk 17 2021-09-14
  - OpenJDK Runtime Environment (build 17+35-2724)
  - OpenJDK 64-Bit Server VM (build 17+35-2724, mixed mode, sharing)

### Version

3.2.0

**Comment by hermanbarrantes** [comment]
The same happens when creating a lambda function

`mn create-app example.micronaut.ping --features aws-lambda,graalvm`

Then

`gradlew.bat buildNativeLambda`

The produced DockerfileNative has the same path issue

```Dockerfile
FROM amazonlinux:latest AS graalvm
ENV LANG=en_US.UTF-8
RUN yum install -y gcc gcc-c++ libc6-dev zlib1g-dev curl bash zlib zlib-devel zlib-static zip tar gzip
RUN curl -4 -L https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.3.0/graalvm-ce-java11-linux-amd64-21.3.0.tar.gz -o /tmp/graalvm-ce-java11-linux-amd64-21.3.0.tar.gz
RUN tar -zxf /tmp/graalvm-ce-java11-linux-amd64-21.3.0.tar.gz -C /tmp && mv /tmp/graalvm-ce-java11-21.3.0 /usr/lib/graalvm
RUN rm -rf /tmp/*
RUN /usr/lib/graalvm/bin/gu install native-image
CMD ["/usr/lib/graalvm/bin/native-image"]
ENV PATH=/usr/lib/graalvm/bin:${PATH}
FROM graalvm AS builder
WORKDIR /home/app
COPY layers/libs /home/app/libs
COPY layers/resources /home/app/resources
COPY layers/application.jar /home/app/application.jar
RUN mkdir /home/app/config-dirs
COPY config-dirs/generateResourcesConfigFile /home/app/config-dirs/generateResourcesConfigFile
RUN native-image -cp C:\SOME\WINDOWS\PATH\ping\home\app\libs\*.jar;C:\SOME\WINDOWS\PATH\code\ping\home\app\resources:\home\app\application.jar --no-fallback -H:Name=application -H:ConfigurationFileDirectories=C:\SOME\WINDOWS\PATH\code\ping\home\app\config-dirs\generateResourcesConfigFile -H:Class=io.micronaut.function.aws.runtime.MicronautLambdaRuntime
FROM amazonlinux:latest
WORKDIR /function
RUN yum install -y zip
COPY --from=builder /home/app/application /function/func
RUN echo "#!/bin/sh" >> bootstrap && echo "set -euo pipefail" >> bootstrap && echo "./func -XX:MaximumHeapSizePercent=80 -Dio.netty.allocator.numDirectArenas=0 -Dio.netty.noPreferDirect=true -Djava.library.path=$(pwd)" >> bootstrap
RUN chmod 777 bootstrap
RUN chmod 777 func
RUN zip -j function.zip bootstrap func
ENTRYPOINT ["/function/func"]
```
On line 17

`RUN native-image -cp C:\SOME\WINDOWS\PATH\ping\home\app\libs\*.jar;C:\SOME\WINDOWS\PATH\code\ping\home\app\resources:\home\app\application.jar --no-fallback -H:Name=application -H:ConfigurationFileDirectories=C:\SOME\WINDOWS\PATH\code\ping\home\app\config-dirs\generateResourcesConfigFile -H:Class=io.micronaut.function.aws.runtime.MicronautLambdaRuntime
`

**Comment by ilopmar** [comment]
A user reported on Gitter that this still happens with 3.2.0

**Comment by melix** [comment]
I have found the problem. We're using the GraalVM plugin's `NativeImageCommandLineProvider` in order to generate the CLI invocation. However, this is supposed to be used on the same platform as the host, which isn't the case when a Windows machine starts a docker container.

Looking for a fix.

**Comment by hci2** [comment]
Thank you for fixing the issue!
