### ISSUE TITLE
Http Client is not included by default

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-gradle-plugin#38]
Micronaut HTTP Client is not included by default and it probably should be because Starter includes it.

- `git clone https://github.com/micronaut-graal-tests/micronaut-basic-app`
- `cd micronaut-basic-app`
- `git checkout micronaut-gradle-plugin`
- Comment out this dependency manually included `implementation "io.micronaut:micronaut-http-client"`
- `./gradlew run`

The application fails to compile because of missing HTTP Client.

**Comment by graemerocher** [comment]
This is not something that makes sense to include by default and should be declared to by the user IMO
