### ISSUE TITLE
Logback is not included by default

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-gradle-plugin#39]
No logging dependency is included by default. Logback should be included.

- `git clone https://github.com/micronaut-graal-tests/micronaut-basic-app`
- `cd micronaut-basic-app`
- `git checkout micronaut-gradle-plugin`
- Edit `build.gradle` and remove the logback dependency
- `./gradlew run`

Nothing is displayed when the application starts up, only the warning message.

```
> Task :run
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

**Comment by graemerocher** [comment]
logging is not something we can make automatic decisions about
