### ISSUE TITLE
Micronaut AOT + shadow

### ISSUE THREAD

**Issue by altro3** [micronaut-projects/micronaut-gradle-plugin#416]
### Feature description

At the moment, the AOT plugin can generate zip files with a bunch of jar files inside. If I include the shadow plugin, then one fat jar is generated, but it does not contain optimizations.

I think it would be right to extend the optimizations to the fat jar too

**Comment by melix** [comment]
This task already exists: the task which produces an AOT optimized fat jar is called `optimizedJitJarAll`.

**Comment by melix** [comment]
I'm closing this issue (see comment above). Let me know if it doesn't fix your problem.

**Comment by altro3** [comment]
@melix Hi! Sorry for long answer. That's right, there is such a task, but it's not exactly the same. So, I will explain: now, if I run a build task, I get a set of different types of builds in the distributions folder:

![изображение](https://user-images.githubusercontent.com/48474279/161420572-9efbc789-b7b1-4f96-922c-e6a408e9fbbe.png)

I see `simple build`, `optimized build`, `shadow build`, but I don't see `optimized-shadow build`.

But if you look ot libs directory, you will see next jars:
![изображение](https://user-images.githubusercontent.com/48474279/161420669-d35e6d5f-b13c-4b41-930f-6826ed730e67.png)
I ask you to add the generation of an optimized shadow build to the distributions folder

**Comment by melix** [comment]
I see, so you're basically looking for start scripts in this case right? Because you can run the shadow jar directly with `java -jar`, so I guess what you're looking for is a distribution zip with start scripts and a single jar in it?

**Comment by altro3** [comment]
Yes, the problem is not that the jar file is not being created. Simply, there is not enough full-fledged distribution with an optimized-shadow artifact inside. Of course, this is not a critical error, because not everyone uses the zip artifact, but most use the jar file from the libs folder
