### ISSUE TITLE
Can't run jar application

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-gradle-plugin#42]
I've generated and application with the Starter using branch `gradle-plugin` with:

```
./gradlew micronaut-cli:run --args="create-app com.example.foo"
```

Executing `./gradlew assemble` task generates in `build/lib`:

```
-rw-rw-r-- 1 ivan ivan 1451 Sep 23 13:56 foo-0.1.jar
-rw-rw-r-- 1 ivan ivan 1430 Sep 23 13:56 foo-0.1-runner.jar
```

But none of those files are runnable. Is it mandatory for the user to include the shadowJar plugin? In that case Starter should include it automatically.

Note that `./gradlew run` works properly.

**Comment by graemerocher** [comment]
You can use:

```
java -jar build/layers/application.jar
```

**Comment by ilopmar** [comment]
The problem with this approach is that the application is not "portable":

```
-rw-rw-r-- 1 ivan ivan 1551 Sep 23 14:39 application.jar
drwxrwxr-x 2 ivan ivan 4096 Sep 23 14:39 libs
drwxrwxr-x 2 ivan ivan 4096 Sep 23 14:39 resources
```

The jar is still not runable itself, it depends on the `libs` and `resources` directories.
If this is the final approach I think at least we should document that users need to add manually shadowJar to have the old behavior. I see a lot of support questions on gitter or issues asking about this.

**Comment by graemerocher** [comment]
Absolutely, needs documentation for sure. For new apps I don't believe shadow jar is a sensible default as it eliminates the possibility to do docker layering and shadow jar itself has introduced problems in the past as there are complexities when it comes to merging jars (for example libraries that read the `Implementation-Version` from `META-INF` break)

**Comment by ilopmar** [comment]
Removing shadow jar as a default means that we think that the majority of our users deploy their applications as docker containers, which I personally don't think it's the case.

**Comment by graemerocher** [comment]
Like I said it is not just about docker, producing a fat/shadow JAR using the existing shadow Gradle plugin also has numerous issues, for example we had a segfault occuring at one point with CLI apps due to how jansi was incorrectly merged into a single JAR. 

Apart from that, that is an interesting claim, so you believe the majority of users are deploying to VMs and running `java -jar` within a VM?

**Comment by ilopmar** [comment]
> Apart from that, that is an interesting claim, so you believe the majority of users are deploying to VMs and running java -jar within a VM?

Yes, a VM, managed cloud instances, AWS elastic beanstalk,... 

Maybe we can add a new feature to Starter for users that want a runable fatjar ready to use.

**Comment by graemerocher** [comment]
There is already a feature for this, it is just a matter of making it visible which it is not at the moment for whatever reason https://github.com/micronaut-projects/micronaut-starter/blob/2.0.x/starter-core/src/main/java/io/micronaut/starter/feature/other/ShadePlugin.java#L40

**Comment by sdelamo** [comment]
> Apart  from that, that is an interesting claim, so you believe the majority of users are deploying to VMs and running java -jar within a VM?

I think so as well.  

I think we should include shade by default.

We have example of deployments of a FAT JAR to different clouds: 

- [AWS Elasticbeanstalk](https://guides.micronaut.io/micronaut-elasticbeanstalk/guide/index.html)
- [AWS Lambda](https://guides.micronaut.io/tags//aws-lambda.html)
- [Microsoft Azure](https://guides.micronaut.io/micronaut-azure-cloud/guide/index.html)
- [Google App Engine Java Flexible Environment](https://guides.micronaut.io/micronaut-gradle-google-cloud/guide/index.html)

**Comment by graemerocher** [comment]
Surely with those though it is just as easy to copy everything up that is in `build/layers`?

**Comment by jameskleeh** [comment]
I don't think we should be forcing users to change how they deploy by default. I think it's a common expectation at this point that a single fat jar will be produced. It has been that way since the beginning. Not meeting that expectation will lead to confusion, even with proper documentation. Is there a harm in creating a fat jar in addition to the layers by default?

**Comment by graemerocher** [comment]
I am fine with restoring shadow plugin applied by default for launch, even if it is bad practise IMO and has issues.

**Comment by wetted** [comment]
I think in any case, if shade is default (and that makes sense if it's been that way before) there should be a way to disable part of it.

**Comment by alvarosanchez** [comment]
@graemerocher if we were to switch to Jib for Docker builds, wouldn't we be able to keep the fat jar?

**Comment by graemerocher** [comment]
I think the shadow plugin for Gradle is ok in that it builds an additional jar with `-all` so you can add Jib or this plugin to build the layers are you are fine.

The situation for the Maven plugin is worse since when you apply the shade plugin it replaces the built JAR with the shaded version so you can't actually build a non-shaded version.

**Comment by graemerocher** [comment]
I have restored in the PR that shadow is applied by default https://github.com/micronaut-projects/micronaut-starter/pull/475/commits/46c56330a4635b82443167b9215026c774141b0c

We can leave this like this for now for 2.1, however when 2.2 is released we will need to figure out how to handle Maven which I am unsure of

**Comment by ilopmar** [comment]
Then we need to revert this https://github.com/micronaut-projects/micronaut-gradle-plugin/commit/63b1f0a8c9821b696a6196378d1778c60e427b1d

**Comment by graemerocher** [comment]
I don't think that needs to be reverted, by default the plugin does not apply the Shadow plugin itself, it is up to the user (or Micronaut Launch) to apply it

**Comment by graemerocher** [comment]
I don't think it is the right thing to do for this plugin to apply the shadow plugin because then users cannot un-apply it

**Comment by ilopmar** [comment]
Yes, giving it a second thought, you are right.
