### ISSUE TITLE
Custom CA (PEM or CERT) on Docker Build

### ISSUE THREAD

**Issue by driverpt** [micronaut-projects/micronaut-gradle-plugin#427]
### Feature description

Currently we are using a Corporate Proxy that requires custom CA Authority to be installed for SSL to work properly, resulting in errors like this one:

Command:
```
./gradlew buildNativeLambda -Pmicronaut.runtime=lambda
```

Output:
```
https://cdn.amazonlinux.com/2/core/2.0/x86_64/76a55ba3ad797033f12ba757bd259d6c315586d38db8c55e6669f36d326b3c1d/repodata/repomd.xml?instance_id=URLError&region=unknown: [Errno 14] curl#60 - "SSL certificate problem: unable to get local issuer certificate"
Trying other mirror.
```

Is it possible to "inject" a `.pem` or `.cer` with Custom CA Authority to be automatically installed?

Thanks

**Comment by melix** [comment]
You should be able to tweak the generated file doing something like this:

```gradle
tasks.named('dockerfileNative') {
    doLast {
    	def dockerFile = destFile.get().asFile
    	def lines = dockerFile.readLines()
    	lines.add(2, "COPY mycert.crt /path/to/mycert")
    	dockerFile.text = lines.join("\n")
    }
}
```

**Comment by driverpt** [comment]
@melix , can we just add `-k` to curl and
```
RUN echo "ssl_verify=false" >> /etc/yum.conf
```

?

**Comment by melix** [comment]
Not sure what you're talking about, there's no `curl` in default docker files the plugin creates. If there was, I don't think it would be a good idea to disable certificate verification in any case, it's a security issue.

So I would recommend you put your certificate files somewhere in your source tree and add something to install certificates in your docker image. I am unfortunately not a Docker expert so I'm not sure how this is doable in practice, but [this link](https://stackoverflow.com/questions/42292444/how-do-i-add-a-ca-root-certificate-inside-a-docker-image) might help.

**Comment by driverpt** [comment]
Update, this worked:

```
    doLast {
        def dockerFile = destFile.get().asFile
        def lines = dockerFile.readLines()
        lines.add(2, "RUN echo \"sslverify=false\" >> /etc/yum.conf")
        lines[4] = lines[4].replace("-4", "-k -4")
        dockerFile.text = lines.join("\n")
    }
```

Thanks
