### ISSUE TITLE
Cannot configure micronaut in kotlin buildSrc after upgrading to 3.3.0

### ISSUE THREAD

**Issue by hassomehide** [micronaut-projects/micronaut-gradle-plugin#438]
### Expected Behavior

I am using gradle's buildSrc feature to apply common traits to the modules in my multi-module project. This includes applying a common Micronaut configuration (version, runtime, testRuntime etc). This has worked well with the gradle plugin version 3.2.2.

### Actual Behaviour

After upgrading to 3.3.0+, the following error appears when building the project:

```
e: [...]/sample/buildSrc/src/main/kotlin/test.gradle.kts: (6, 5): Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
public infix fun PluginDependencySpec.version(version: String?): PluginDependencySpec defined in org.gradle.kotlin.dsl
public infix fun PluginDependencySpec.version(version: Provider<String>): PluginDependencySpec defined in org.gradle.kotlin.dsl
```

Seems like the io.micronaut.gradle.MicronautExtension class is not available on classpath anymore.

### Steps To Reproduce

Bare minimum gradle project to reproduce the issue looks something like this:

sample/buildSrc/build.gradle.kts

```
plugins {
    `kotlin-dsl`
}

repositories {
    gradlePluginPortal()
}

dependencies {
    implementation("io.micronaut.gradle:micronaut-gradle-plugin:3.3.0")
}
```

sample/buildSrc/src/main/kotlin/test.gradle.kts

```
plugins {
    id("io.micronaut.minimal.library")
}

micronaut {
    version("3.4.1")
}
```

### Environment Information

```
$ ./gradlew -v

------------------------------------------------------------
Gradle 7.4.2
------------------------------------------------------------

Build time:   2022-03-31 15:25:29 UTC
Revision:     540473b8118064efcc264694cbcaa4b677f61041

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.2 (Azul Systems, Inc. 17.0.2+8-LTS)
OS:           Mac OS X 12.3.1 aarch64
```

### Version

3.4.1

**Comment by melix** [comment]
Thanks for the report. I think the problem comes from the fact we're using `implementation` dependencies instead of API for the gradle plugin. Workaround is to use this dependency instead:

```gradle
dependencies {
    implementation("io.micronaut.gradle:micronaut-minimal-plugin:3.3.2")
}
```
