### ISSUE TITLE
Add ability to change platform bom for project

### ISSUE THREAD

**Issue by altro3** [micronaut-projects/micronaut-gradle-plugin#444]
### Feature description

It is currently not possible to replace platform and always uses micronaut-bom. The problem is that I want to use micronaut as a platform, but not all versions of the libraries that are used in the project are present there. I would like to use my own bom file which includes micronaut-bom and the libraries I need in my projects.

Please add this feature!

**Comment by melix** [comment]
There is a `micronautBoms` configuration that you can use to declare your BOM. If you want to totally get rid of the Micronaut BOM, you should be able to do something like this:

```
micronautBoms.dependencies.clear()

dependencies {
    micronautBoms "your bom"
}
```
