### ISSUE TITLE
Usage of platform micronaut-bom in custom scopes

### ISSUE THREAD

**Issue by morki** [micronaut-projects/micronaut-gradle-plugin#45]
Please is it possible to use micronaut-bom in custom scope like `jooqGenerator`?
I would like to not set postgres version manually like:

```kotlin
jooqGenerator("org.postgresql:postgresql:42.2.14")
```

Thank you for reply.

**Comment by ilopmar** [comment]
Yes, you can probably do something like:

```
jooqGenerator(platform("io.micronaut:micronaut-bom:$micronautVersion"))
jooqGenerator("org.postgresql:postgresql")
```

See https://github.com/micronaut-graal-tests/micronaut-jooq-graal/blob/f7b6d3ca9072d9d45a77d85a4a868303d8867bb4/build.gradle#L46-L47
