### ISSUE TITLE
developmentOnly configuration is only included when `-t` flag is used

### ISSUE THREAD

**Issue by musketyr** [micronaut-projects/micronaut-gradle-plugin#466]
### Expected Behavior

When I have dependency in `developmentOnly` configuration then it is included when running using `./gradlew run` command.

### Actual Behaviour

The `developmentOnly` dependency is only present when `-t` flag is added to the command line options.

### Steps To Reproduce

1. `mn create-app console-demo`
2. add `developmentOnly("com.agorapulse:micronaut-console:2.0.1-micronaut-3.0")` dependency 
3. run the application
4. execute `curl http://localhost:8080/console/dsl/text`
5. the result should be the list of available variables for the script, not 404

### Environment Information

JDK 8
Micronaut 3.5.0-SNAPSHOT

### Example Application

https://github.com/musketyr/micronaut-development-only-issue

### Version

3.5.0-SNAPSHOT

**Comment by musketyr** [comment]
ping @sdelamo

**Comment by melix** [comment]
I am not convinced we should do this. The "development mode" is when continuous mode is active. Without `-t` we can't make a difference between a regular build and a build which should mix in `developmentOnly` dependencies. What is your use case?

**Comment by musketyr** [comment]
in this PR https://github.com/micronaut-projects/micronaut-starter/pull/1207#pullrequestreview-965401074 @sdelamo suggested to use `developmentOnly` to ensure that the `micronaut-console` won't make it into the deployed application unless explicitly requested. but it should be still present when you run `./gradlew run` which is for example the default when you launch the application from the IDE.

**Comment by sdelamo** [comment]
I strongly believe that running `./gradlew run` should be development mode as well. And I think that would be the case for many users.  Continuous  mode will not be for everyone. Moreover, many users will have no idea about it. 

I am in production mode, when I generate an artifact a FAT JAR or native image of my app. 

`run` => dev mode
`test`=> test mode
`shadowJar` => prod mode
`nativeCompile` => prod mode

**Comment by melix** [comment]
There are drawbacks in making `run` a "development aware" mode. In particular, the `developmentOnly` dependencies would precisely pollute the user classpath. It means that for example if you'd run the native agent to generate reflection configuration, you'd get the wrong application classpath, it would contain development only dependencies, which is wrong.

In addition, this would put file watching libraries on classpath even if `run` doesn't use them. It would also add those libraries to the AOT classpath analysis I think (must double check), which is also wrong.

I am clearly not convinced that `run` should do this.

**Comment by musketyr** [comment]
just to be sure that when the `3.5.0` is released with the new Micronaut Console then it would work out of the box, I have created the PR to switch back to runtime dependency https://github.com/micronaut-projects/micronaut-starter/pull/1240

**Comment by sdelamo** [comment]
I think the first thing to do is to document what [`developmentOnly` is and how to run it](https://github.com/micronaut-projects/micronaut-gradle-plugin/issues/467`)

**Comment by sdelamo** [comment]
One thing that I am confused is that if I [generate an application with `lambda`](https://micronaut.io/launch?type=DEFAULT&name=demo&package=com.example&javaVersion=JDK_11&lang=JAVA&build=GRADLE&test=JUNIT&features=aws-lambda&version=3.4.4) which gets [`api-proxy-test` dependency as developmentOnly](https://github.com/micronaut-projects/micronaut-gradle-plugin/blob/master/minimal-plugin/src/main/java/io/micronaut/gradle/MicronautRuntimeDependencies.java#L68)

I run `./gradlew run`. The app starts thanks to `proxy-test`. 

```

17:19:21.862 [main] INFO  org.eclipse.jetty.util.log - Logging initialized @1095ms to org.eclipse.jetty.util.log.Slf4jLog
17:19:21.933 [main] INFO  i.m.f.a.p.AbstractLambdaContainerHandler - Starting Lambda Container Handler
17:19:21.943 [main] INFO  i.m.context.env.DefaultEnvironment - Established active environments: [function, lambda]
17:19:22.683 [main] INFO  org.eclipse.jetty.server.Server - jetty-9.4.35.v20201120; built: 2020-11-20T21:17:03.964Z; git: bdc54f03a5e0a7e280fab27f55c3c75ee8da89fb; jvm 11.0.15+10-jvmci-22.1-b06
17:19:22.712 [main] INFO  o.e.jetty.server.AbstractConnector - Started ServerConnector@31add175{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
17:19:22.712 [main] INFO  org.eclipse.jetty.server.Server - Started @1948ms
17:19:22.713 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 1232ms. Server Running: http://localhost:8080

```

Thus, in that scenario I don't seem to need any `-t`. @melix do you have an explanation for this?

**Comment by melix** [comment]
So I checked and indeed, `developmentOnly` dependencies are added even without `-t`. So I guess this issue should be closed?

**Comment by musketyr** [comment]
But do we have other explanation to the issue above? Why the console controller is only active when `-t` is used?

**Comment by musketyr** [comment]
@melix I have just tried to reach the class from the running application without `-t` and the app thrown `ClassNotFoundException`:

```
Class.forName("com.agorapulse.micronaut.console.http.ConsoleController");
```

When I do the same with `-t` flag then no exception is thrown.

This still looks to me that the dependency is not on the classpath when `-t` is not used.

**Comment by musketyr** [comment]
there is some weird magic going on behind the scenes. when I try this repeatedly then sometimes it does not work on the fresh project and sometimes it does.

**Comment by melix** [comment]
I will check how this is wired in the plugin, but this sounds like an ordering issue (like with `afterEvaluate`)

**Comment by melix** [comment]
Sorry for the long delay. I see nothing obvious which would explain that it sometimes work, sometimes not. I have tried your repro and it works as expected. Would be nice if you had build scans when it works and when it doesn't, so that we can compare.
