### ISSUE TITLE
src/main/graal/reflect.json is not working

### ISSUE THREAD

**Issue by navrocky** [micronaut-projects/micronaut-gradle-plugin#497]
### Expected Behavior

As I see here https://objectcomputing.com/files/9915/5654/3804/Slide_Deck_Micronaut_and_GraalVM_Webinar.pdf there is a `src/main/graal/reflect.json` file  to define user's reflection definitions.

### Actual Behaviour

But there is no effect.

Generation of reflection-config.json was removed here: https://github.com/micronaut-projects/micronaut-core/pull/5564 
But only resource-config.json generation was added in micronaut gradle plugin here: https://github.com/micronaut-projects/micronaut-gradle-plugin/pull/215

### Environment Information

- opensuse thumbleweed
- graalvm 22.1.0.r11-grl

### Version

3.5.2

**Comment by melix** [comment]
Custom `reflect-config.json`, if needed, can be added directly to `src/main/resources/META-INF/native-image/your.group/your.artifact/reflect-config.json`.

**Comment by luisospina-sealed** [comment]
@melix, sorry to use this thread, but, I'm adding a custom `reflect-config.json` file in `src/main/resources/META-INF/native-image/com.example/demo/reflect-config.json` folder and I don't see it in the `build/docker/native-main` folder files nor included in the DockerfileNative as `-HreflectionConfigurationFiles` when running **dockerBuildNative** command.
is it part of any other command? I can't find that in the documentation

**Comment by graemerocher** [comment]
@luisospina-sealed can you report a separate issue if this doesn't take effect in docker

**Comment by melix** [comment]
>  I don't see it in the build/docker/native-main folder files nor included in the DockerfileNative as -HreflectionConfigurationFiles when running dockerBuildNative command.

This shouldn't be required since the resource will be packaged in the `application.jar` file :thinking:

**Comment by luisospina-sealed** [comment]
This was my fault, not sure what I was doing wrong but I started it from scratch in a new project and I see the file is being copied to: `build/docker/native-main/layers/resources` and it works even if no `-HreflectionConfigurationFiles` is specified in the Dockerfile.
also, @graemerocher, I came into this issue trying a workaround to fix this https://github.com/micronaut-projects/micronaut-r2dbc/issues/273 (Micronaut R2DBC with GraalVM native image)
