### ISSUE TITLE
All Gradle tasks log extra messages since 3.5.0

### ISSUE THREAD

**Issue by levee223** [micronaut-projects/micronaut-gradle-plugin#506]
### Expected Behavior

Behavior similar to 3.4.1.

### Actual Behaviour

All Gradle tasks log the following extra messages:
```
> Configure project :
[native-image-plugin] Instrumenting task with the native-image-agent: test
[native-image-plugin] Instrumenting task with the native-image-agent: testNativeImage
```

### Steps To Reproduce

1. Generate a demo project with default options using Micronaut Launch.
2. Bump Micronaut Gradle Plugin to 3.5.0.
   ```diff
   --- demo-gradle-plugin-3.4.1/build.gradle       2022-07-16 08:48:50.000000000 +0000
   +++ demo-gradle-plugin-3.5.0/build.gradle       2022-07-16 17:52:21.880077795 +0000
   @@ -1,6 +1,6 @@
    plugins {
        id("com.github.johnrengelman.shadow") version "7.1.2"
   -    id("io.micronaut.application") version "3.4.1"
   +    id("io.micronaut.application") version "3.5.0"
    }

    version = "0.1"
   ```
3. Run any gradle task.
   ```
   ~/demo-gradle-plugin-3.4.1$ ./gradlew clean

   BUILD SUCCESSFUL in 367ms
   1 actionable task: 1 executed
   ```

   ```
   ~/demo-gradle-plugin-3.5.0$ ./gradlew clean

   > Configure project :
   [native-image-plugin] Instrumenting task with the native-image-agent: test
   [native-image-plugin] Instrumenting task with the native-image-agent: testNativeImage

   BUILD SUCCESSFUL in 377ms
   1 actionable task: 1 executed
   ```

### Environment Information

- Ubuntu 20.04.4 LTS
- OpenJDK Runtime Environment (build 17.0.3+7-Ubuntu-0ubuntu0.20.04.1)

### Version

Micronaut: 3.5.3, Micronaut Gradle Plugin: 3.5.0

**Comment by melix** [comment]
This should be an issue created on https://github.com/graalvm/native-build-tools/ since this is the plugin which adds logs.

**Comment by melix** [comment]
Indeed. So there are 2 issues: one is the extra logging, which should be reported to the NBT repo. And this one, which is that the Micronaut Gradle plugin eagerly configures some tasks probably, which triggers those messages to be printed at configuration time.
