### ISSUE TITLE
Upgrade Micronaut Gradle Plugin to use GraalVM v22.2.0

### ISSUE THREAD

**Issue by dmahapatro** [micronaut-projects/micronaut-gradle-plugin#516]
### Expected Behavior

I expect when I build native AWS Lambda, I should be able to use the latest version of GraalVM or configure the GraalVM version in `build.gradle`.

### Actual Behaviour

`./gradlew buildNativeLambda` still uses GraalVM v22.1.0, even if locally v22.2.0 is installed.

The `DockerfileNative` refers to 22.1.0

### Steps To Reproduce

**Step 1:**
Install GraalVM v22.2.0. Using sdkman it would look like:
`sdk install java 22.2.r17-grl`

**Step 2:**
```
mn create-app --build=gradle --jdk=17 --lang=java --test=junit --features=graalvm,aws-lambda-custom-runtime,aws-lambda com.example.demo
```

**Step 3:**
`./gradlew buildNativeLambda`

### Environment Information

Operating System: MacOS Monterey 12.4

JDK
openjdk version "17.0.4" 2022-07-19
OpenJDK Runtime Environment GraalVM CE 22.2.0 (build 17.0.4+8-jvmci-22.2-b06)
OpenJDK 64-Bit Server VM GraalVM CE 22.2.0 (build 17.0.4+8-jvmci-22.2-b06, mixed mode, sharing)

Source Code that needs to change:
https://github.com/micronaut-projects/micronaut-gradle-plugin/blob/master/docker-plugin/src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java#L61

### Version

3.6.0

**Comment by jigneshkhatri** [comment]
@melix How can we mention the custom GraalVM version to be used to build the native image? I want to build the native image of my project using the GraalVM enterprise which is installed on my local machine, but it seems like it is always downloading GraalVM CE when trying to building docker native image. Here is the full detailed version of my question: https://stackoverflow.com/questions/74601868/choose-custom-graalvm-version-to-build-micronaut-native-image
