### ISSUE TITLE
Create Gradle tasks for CRaC `dockerBuildCrac` and `dockerPushCrac`

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-gradle-plugin#523]
### Issue description

this issue can be moved to the gradle plugin once we have a full milestone of CRaC. 

https://micronaut-projects.github.io/micronaut-gradle-plugin/latest/#_docker_support

It would be good to create a custom Gradle tasks similar to what we do for GraalVM with `dockerBuildNative` and `dockerPushNative` but for CRaC. 

E.g.  `dockerBuildCrac` and `dockerBuildPushCrack`. It would create a Jar, run, make a checkpoint and the entry point would be the restoration from the checkpoint.

**Comment by graemerocher** [comment]
These tasks should be placed in a new optional plugin as not to bloat the existing plugins

**Comment by timyates** [comment]
So we have `dockerBuildCrac`, but currently no `dockerBuildPushCrac`...  Is this a requirement?

**Comment by sdelamo** [comment]
> So we have `dockerBuildCrac`, but currently no `dockerBuildPushCrac`... Is this a requirement?

Yes. 

We should have parity to the other docker tasks. 

> dockerPush - Pushes a Docker Image to configured container registry

> dockerPushNative - Pushes a Docker Image built with GraalVM Native Image to configured container registry

We should have 

`dockerPushCrac` - Pushes a Docker Image built with ....... to configured container registry

**Comment by timyates** [comment]
Done in 3.6.0
