### ISSUE TITLE
Change ownership of Micronaut Gradle Plugins

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-gradle-plugin#546]
Currently, We distribute Micronaut Gradle plugins to the Gradle plugin portal with @graemerocher as the owner. 

https://plugins.gradle.org/u/graemerocher

We should create an account for the Micronaut Foundation (for example [SpringIO plugins](https://plugins.gradle.org/u/spring)), and save the credentials at 1Password. That new account should be the owner of the plugins. We should check if an ownership transfer is possible.

**Comment by sdelamo** [comment]
I have created an [account in the gradle plugin portal](https://plugins.gradle.org/u/micronaut).

**Comment by melix** [comment]
It is likely that after the change of ownership, the 1st release will require manual action from the Gradle team to validate the plugins.

**Comment by sdelamo** [comment]
> It is likely that after the change of ownership, the 1st release will require manual action from the Gradle team to validate the plugins.

the Gradle team helped me with the migration. 

Micronaut Framework Gradle plugins are now under [`micronaut`](https://plugins.gradle.org/u/micronaut) owner. 

I have updated the Github Secrets `GRADLE_PUBLISH_KEY ` and `GRADLE_PUBLISH_SECRET` accordingly.
