### ISSUE TITLE
Allow customising the ENTRYPOINT for dockerfileNative

### ISSUE THREAD

**Issue by alvarosanchez** [micronaut-projects/micronaut-gradle-plugin#559]
Now, the `ENTRYPOINT` instruction is added unconditionally: https://github.com/micronaut-projects/micronaut-gradle-plugin/blob/master/docker-plugin/src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java#L479-L484

So when doing:

```groovy
dockerfileNative {
    entryPoint("foo")
}
```

The generated dockerfile contains 2 entrypoint instructions.

**Comment by melix** [comment]
The code that you are referring to is for the lambda use case. Is there a reason to override the entry point here? Not saying we shouldn't but I'm trying to understand the use cases.

**Comment by alvarosanchez** [comment]
This is too old and I can't remember the use case. Closing it for now
