### ISSUE TITLE
buildNativeLambda job failing after upgrading to 3.6.2

### ISSUE THREAD

**Issue by vladas** [micronaut-projects/micronaut-gradle-plugin#566]
### Expected Behavior

Building native image:

https://paste-bin.xyz/85032

### Actual Behaviour

Fails https://paste-bin.xyz/85033

### Steps To Reproduce

The GitHub action I use:

     - name: Build with Gradle
        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
        with:
          arguments: :bot-api:buildNativeLambda

other settings from `build.gradle.kts`:

    graalvmNative {
        toolchainDetection.set(false)
    
        metadataRepository {
            enabled.set(true)
        }
    
        binaries {
            named("main") {
            }
        }
    }

### Environment Information

GraalVM version:

      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.1.0'
          java-version: '17'
          components: 'native-image'

### Version

3.7.1

**Comment by melix** [comment]
I think this has been fixed in a newer release. Please reopen if you still see the problem on the latest 3.7 release.
