### ISSUE TITLE
Micronaut Gradle Plugin should leverage GraalVM reachability Metadata repository 

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-gradle-plugin#567]
see: https://github.com/oracle/graalvm-reachability-metadata

**Comment by melix** [comment]
This is a pre-requisite for https://github.com/micronaut-projects/micronaut-core/issues/7805 but it can be activated independently (which is what I do for testing).

**Comment by sdelamo** [comment]
@melix can this be closed? Or do we still need to do work?

**Comment by melix** [comment]
Yes, this is implemented in `4.0.0-M1` already.
