### ISSUE TITLE
JUnit tag exclusion has no effect

### ISSUE THREAD

**Issue by tommi-l** [micronaut-projects/micronaut-gradle-plugin#57]
Adding the plugin to a minimal project (created with `mn` CLI) seems to somehow disable JUnit tag filtering. 

Test annotations:
```Java
@MicronautTest
@Tag("someTag")
```

`build.gradle` config:
```Groovy
plugins {
    id "io.micronaut.application" version "1.0.3"
...

test {
    useJUnitPlatform {
        excludeTags 'someTag'
    }
}
```

This results in `someTag` tests to be executed with the `test` task. Does that make sense?

**Comment by mihai97ionita** [comment]
I encounter the same problem. Excluded tags seems to be ignored, same thing for included tags.
