### ISSUE TITLE
`dockerfileNative` and `generateResourcesConfigFile` disagree

### ISSUE THREAD

**Issue by jrw972** [micronaut-projects/micronaut-gradle-plugin#578]
### Expected Behavior

The `dockerfileNative` task should produce a viable Dockerfile.

### Actual Behaviour

The `dockerfileNative` task produced this output (snippet)

```
> Task :app:generateResourcesConfigFile
[native-image-plugin] Resources configuration written into .../app/build/native/generated/generateResourcesConfigFile/resource-config.json
```

and 
Dockerfile (at `app/build/docker/native-main/DockerfileNative`)

```
FROM ghcr.io/graalvm/native-image:ol7-java11-22.2.0 AS graalvm
WORKDIR /home/app
COPY layers/libs /home/app/libs
COPY layers/classes /home/app/classes
COPY layers/resources /home/app/resources
COPY layers/application.jar /home/app/application.jar
RUN mkdir /home/app/config-dirs
COPY config-dirs/generateResourcesConfigFile /home/app/config-dirs/generateResourcesConfigFile
RUN native-image -cp /home/app/libs/*.jar:/home/app/resources:/home/app/application.jar --no-fallback -H:Name=application -J--add-exports=org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk=ALL-UNNAMED -J--add-exports=org.graalvm.nativeimage.builder/com.oracle.svm.core.configure=ALL-UNNAMED -J--add-exports=org.graalvm.sdk/org.graalvm.nativeimage.impl=ALL-UNNAMED -H:ConfigurationFileDirectories=/home/app/config-dirs/generateResourcesConfigFile -H:Class=io.unityfoundation.dds.permissions.manager.RunApplication
FROM frolvlad/alpine-glibc:alpine-3.12
RUN apk --no-cache update && apk add libstdc++
EXPOSE 8080
COPY --from=graalvm /home/app/application /app/application
ENTRYPOINT ["/app/application"]
```

The relevant lines are
```
RUN mkdir /home/app/config-dirs
COPY config-dirs/generateResourcesConfigFile /home/app/config-dirs/generateResourcesConfigFile
```
When building the image from this Dockerfile, `config-dirs/generateResourcesConfigFile` does not exist.
Presumably, a `config-dirs` directory should exist `app/build/docker/native-main` but it does not.

The `buildNativeLayersTask` also does not produce it.

### Steps To Reproduce

1. Create an app.
2. `./gradlew dockerfileNative buildNativeLayersTask`
3. `docker build -f app/build/docker/native-main/DockerfileNative app/build/docker/native-main`

### Environment Information

- Operating System Version: macOS 12.6

```
java -version
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)
```

```
./gradlew -version
------------------------------------------------------------
Gradle 7.5
------------------------------------------------------------

Build time:   2022-07-14 12:48:15 UTC
Revision:     c7db7b958189ad2b0c1472b6fe663e6d654a5103

Kotlin:       1.6.21
Groovy:       3.0.10
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.11 (AdoptOpenJDK 11.0.11+9)
OS:           Mac OS X 11.5 x86_64
```

### Version

3.7.2

gradle plugin version 3.6.2

**Comment by melix** [comment]
The task which prepares the docker context is `dockerPrepareContext`, which copies the config directories. Any reason you are not using the `dockerbuildNative` task, and running docker manually instead?

**Comment by jrw972** [comment]
I am building an application using Google Cloud Build.  My current process is:
1. Prepare all of the assets and dockerfile using a custom build step that has gradle and node installed.
2. Build the docker image using the `gcr.io/cloud-builders/docker` build step.

I would like to keep this separation of concerns.

**Comment by melix** [comment]
Right, in any case I think the task you're looking for is `dockerPrepareContext`.

**Comment by melix** [comment]
The only reason to use the task directly is if you have custom requirements. In general the `dockerbuildNative` task should suffice.

**Comment by gijsleussink** [comment]
Ok, I'll try that first. There were alternative container builders I want to feed the Gradle output.
