### ISSUE TITLE
Customized Dockerfiles throw an exception

### ISSUE THREAD

**Issue by charlie-harvey** [micronaut-projects/micronaut-gradle-plugin#583]
### Expected Behavior

I should be able to do as the docs say: 

> If you wish to customize the docker builds that are used, the easiest way is to run ./gradlew dockerfile (or dockerfileNative for the native version) and copy the generated Dockerfile from build/docker to your root directory and modify as required.

### Actual Behaviour

When I copy the `build/docker/main/Dockerfile` or the `build/docker/native-main/DockerfileNative` to the project root and run either `./gradlew dockerBuild` or `./gradlew dockerBuildNative` the build fails with the following error.

```
Error during callback
com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Cannot locate specified Dockerfile: /Users/charlesharvey/Software/blammo/Dockerfile"}

        at com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247)
        at com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269)
```

### Steps To Reproduce

1. Checkout repo
2. `./gradlew build` (Dockerfiles have already been copied into root)

### Environment Information

- Operating System: MacOS
- JDK: 17
- Micronaut Gradle Plugin: 3.6.3

### Example Application

https://github.com/charlie-harvey/micronaut-gradle-plugin-custom-dockerfile

### Version

3.7.3

**Comment by bajajyog** [comment]
I am also facing the same issue. Please advise for some workaround or fix for this issue

**Comment by bajajyog** [comment]
I am able to make it work like this. in build.gradle add this :-

task copyDockerFile(type: Copy){
    from ('DockerfileNative1')
    into "${buildDir}/docker/native-main"
    }
}
dockerBuildNative.dockerFile.set(file("${buildDir}/docker/native-main/DockerfileNative1"))

in root dir, copy the docker file. its name is dockerfileNative1
after that, run the native image task
./gradlew clean copyDockerFile  buildNativeLambda

**Comment by charlie-harvey** [comment]
My goal here was to be able to run `keytool -importcert` in the container. But if I add Instructions of any kind they always go at the very end, after the binary has already been built. So first I copy the cert to the right location. Then I set the `optimizedDocerfileNative` task to be disabled. Then I copy in my own `DockerfileNative` that has the `COPY` and `RUN` commands.


```kotlin
tasks {
    val sslCertCopyNativeOptimized = register<Copy>("sslCertCopyNativeOptimized") {
        group = "build"
        description = "Copy the ssl/chain.crt to the build dir"
        from("$projectDir/../ssl/chain.crt")
        into("$buildDir/docker/native-optimized")
    }
    optimizedDockerfileNative {
        enabled = false
    }
    val copyDockerfileNativeToBuildDir = register<Copy>("copyDockerfileNativeToBuildDir") {
        group = "build"
        description = "Copy the DockerfileNative to the build dir"
        from("$projectDir/DockerfileNative")
        into("$buildDir/docker/native-optimized")
    }
    optimizedDockerBuildNative {
        dependsOn(sslCertCopyNativeOptimized)
        dependsOn(copyDockerfileNativeToBuildDir)
        memory.set(14000000000)
    }
}
```

**Comment by graemerocher** [comment]
@melix can you have a look?

**Comment by charlie-harvey** [comment]
Amazing! Thanks so much.

**Comment by melix** [comment]
Release 3.6.5 is out!
