### ISSUE TITLE
BuildLayers Task fails when jars have the same name

### ISSUE THREAD

**Issue by stmty9** [micronaut-projects/micronaut-gradle-plugin#584]
### Expected Behavior

The BuildLayers task should either:

- Gracefully handle duplicate entries using the default (INHERIT) strategy
- Allow the configuration of a [DuplicateStrategy](https://docs.gradle.org/7.5.1/javadoc/org/gradle/api/file/DuplicatesStrategy.html) in the task (or somewhere)

### Actual Behaviour

```
> Task :buildLayers FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildLayers'.
> Entry shared-1.0.0-SNAPSHOT.jar is a duplicate but no duplicate handling strategy has been set. Please refer to https://docs.gradle.org/7.5.1/dsl/org.gradle.api.tasks.Copy.html#org.gradle.api.tasks.Copy:duplicatesStrategy for details.

```

### Steps To Reproduce

1. Create two projects with a 'src' (main) module and a 'shared' module
2. In one of them, depend on both `shared` modules
3. Attempt to run a build

### Environment Information

Mac OSX
Java 17

### Version

3.6.3

**Comment by melix** [comment]
We can definitely add a duplicates strategy to the task. I'm however curious if you have a reproducer for this, because what this hints at is that you have a configuration problem: there shouldn't be any duplicates on classpath.

**Comment by stmty9** [comment]
Thanks for your reply @melix 
I was probably too quick to write up my ticket because I was late for a meeting, but here is gist.
I have two projects with the following module setup:

![modules](https://user-images.githubusercontent.com/4185319/201135414-fa966076-86c6-44d1-9be5-59849fd09545.png)

The dependency structure within a project is as follows:

![dependencies](https://user-images.githubusercontent.com/4185319/201135791-7bf1dde4-a0ae-47a0-af7c-89fc17d332fe.png)

where `client` and `src/main/java` both depend on `shared`.

The purpose of the `client` module is for other services to import and use easily. (since we have switched over to using micronaut, we don't really need this module because we use a declarative client from an interface that the controller in `src/main/java` uses)
The purpose of the `shared` module is to house everything that that both the `client` and `src/main/java` need to function (DTOs, Controller Interfaces, etc).

When `projA` imports the `shared` module from `projB`, there is now a collision (they are both 1.0.0-SNAPSHOT as well).

The workaround is to use more verbose names in our modules, so instead of `shared` it is now `projA-shared` or `projB-shared`. I am personally not a fan of being verbose in the sense that `com.company.projB.projB-shared` is redundant :shrug: .

Hope this helps explain it.
