### ISSUE TITLE
Native executable missing after nativeCompile task

### ISSUE THREAD

**Issue by musketyr** [micronaut-projects/micronaut-gradle-plugin#609]
### Expected Behavior

I'm upgrading project from Micronaut 3.1.1 to 3.7.4 (Gradle plugins from 2.0.6 to 3.6.5).

When I run `./gradlew nativeRun` then the native executables are compiled and the compiled task is run.

### Actual Behaviour

The application executable is not generated, only a header file.

```
A problem was found with the configuration of task ':pierrot:nativeRun' (type 'NativeRunTask'). |  
  | - In plugin 'org.graalvm.buildtools.gradle.NativeImagePlugin$Inject' type 'org.graalvm.buildtools.gradle.tasks.NativeRunTask' property 'image' specifies file '/Users/ladin/development/projects/agorapulse/pierrot/apps/pierrot/build/native/nativeCompile/pierrot' which doesn't exist. |  
  |   |  
  | Reason: An input file was expected to be present but it doesn't exist. |  
  |   |  
  | Possible solutions: |  
  | 1. Make sure the file exists before the task is called. |  
  | 2. Make sure that the task which produces the file is declared as an input. |  
  |   |  
  | Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#input_file_does_not_exist for more details about this problem. |  
 
```

See the build scan for more details

https://scans.gradle.com/s/3kx2olyuyux4o/console-log?anchor=147&page=1

### Steps To Reproduce

1. clone pull request from Pierrot repository https://github.com/agorapulse/pierrot/pull/58
2. install GraalVM `sdk install java 22.3.r11-grl`
3. run `./gradlew nativeRun`

### Environment Information

- Operation system: Darwin aarch64
- Java: OpenJDK 64-Bit Server VM Zulu11.60+19-CA (build 11.0.17+8-LTS, mixed mode)

### Example Application

https://github.com/agorapulse/pierrot/pull/58

### Version

3.7.4

**Comment by melix** [comment]
It appears that you are using a quite old version of Gradle (7.2), you may consider upgrading.

The issue is that between the 2 versions of the plugin, we upgraded the Native Build Tools plugin, which now supports building libraries (`.so`) in addition to applications. However, if you look at your project, you can see that it uses the `java-library` plugin:

https://scans.gradle.com/s/cxjb7g2grtccy/plugins?toggled=WyJqYXZhLWxpYnJhcnktMTMiXQ#java-library::pierrot-13-0

This is a mistake, since an application doesn't expose an API, it must not both apply the `application` and `java-library` plugins (you are either an `application` _or_ a `library`, but not both at the same time).

A workaround is to configure explicitly that you don't want to build a shared library:

```
graalvmNative.binaries.all {
    sharedLibrary = false
}
```

I am not familiar with how your build is setup (with the Kordamp plugins) so you'd know better than me where to put that configuration.

**Comment by musketyr** [comment]
Thanks! That removing `java-library` from the CLI project helped. I'm still getting some other errors but I guess I need to migrate to new way of compiling the binaries and stop using Docker builds.

**Comment by melix** [comment]
What do you mean by "new way of compiling the binaries"? You should call `nativeCompile` to build a native binary, and `dockerBuildNative` to build a native image within a docker container.

**Comment by musketyr** [comment]
the build is using the old approach - calling `native-image` directly from the command line using the generated Shadow JAR.

https://github.com/agorapulse/pierrot/blob/master/.github/workflows/graalvm-snapshot.yml#L38-L49

BTW I haven't seen anything like `distNativeZip` or `distNativeTar` tasks in the tasks list. is the distribution still as easy as grabbing the generated command file and archiving it myself or do I also need any of the header files?

**Comment by melix** [comment]
Creating a custom distribution with the native binary should only be about adding:

```
distributions {
    register("native") {
        contents {
           from(tasks.named("nativeCompile"))
        }
    }
}
```

**Comment by musketyr** [comment]
This works great, thanks. I need a last piece of puzzle - I need to label the archives based on the current operating system to be able to upload them using SDKMAN Vendor API but I can't find out how to reach `org.gradle.nativeplatform.platform.OperatingSystem` instance to do so.

**Comment by melix** [comment]
There is no public API in Gradle to access the operating system (and it's a shame). You can use `org.gradle.internal.os.OperatingSystem#current`, but as the name implies, it's internal.

**Comment by musketyr** [comment]
thanks works well!
