### ISSUE TITLE
dockerBuildNative fails

### ISSUE THREAD

**Issue by bankras** [micronaut-projects/micronaut-gradle-plugin#63]
Running `gradlew dockerBuildNative` on a project fails in step 10/11 with the following  error

```
Could not build image: COPY failed: stat /var/lib/docker/overlay2/c359be076403b377d0b41047e67284d7a39957e65117266c6a8c3e8572b3a38f/merged/home/app/application: no such file or directory
```

In step 7/11 it runs the following command
```
Step 7/11 : RUN native-image -H:Class=counter.Application -H:Name=application --no-fallback -cp /home/app/libs/*.jar:/home/app/resources:/home/app/application.jar
```

According to https://github.com/oracle/graal/issues/726, the `-H:Name` argument here is ignored ending up with a binary name based on the project instead.

**Comment by graemerocher** [comment]
Check whether you have an existing `native-image.properties` file that overrides the name

**Comment by bankras** [comment]
The existing `native-image.properties` in `/src/main/resources/META_INF/native-image/counter/counter-application` is being ignored. The content was already naming a different application name, but the DockerfileNative in `/build/docker` didn't reflect that.

Removing the existing `native-image.properties` gives me the same result in step 10

**Comment by graemerocher** [comment]
That is weird since creating a fresh app from https://micronaut.io/launch doesn't exhibit this behaviour

**Comment by bankras** [comment]
I can confirm that. I've used the CLI tool version 2.1.0

`mn create-app counter --build=gradle --features=mongo-reactive,graalvm --java-version=11 --test=spock`

I cannot find any distinct difference except the micronaut version.
Happy to close this ticket as my issue seems to be resolved with a new launch.
