### ISSUE TITLE
misses `dockerfileCrac` in docs

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-gradle-plugin#637]
### Issue description

In https://micronaut-projects.github.io/micronaut-gradle-plugin/latest/#_micronaut_application_plugin we miss `dockerFileCrac`

> dockerfile - Builds a Docker File for a Micronaut application
> 
> dockerBuild - Builds a Docker Image using the [Docker Gradle plugin](https://github.com/bmuschko/gradle-docker-plugin)
> 
> dockerfileNative - Builds a Docker File for for GraalVM Native Image
> 
> dockerBuildNative - Builds a Native Docker Image using GraalVM Native Image
> 
> dockerBuildCrac - Builds a docker Image containing a CRaC enabled JDK and a pre-warmed, checkpointed application.

**Comment by timyates** [comment]
Closed by https://github.com/micronaut-projects/micronaut-gradle-plugin/pull/641
