### ISSUE TITLE
Possible regression of running tests in 3.7.1

### ISSUE THREAD

**Issue by adamkobor** [micronaut-projects/micronaut-gradle-plugin#643]
### Expected Behavior

Tests should be executed

### Actual Behaviour

Gradle tells that test events were not received. It works without any problem with version 3.7.0.

### Steps To Reproduce

1. Bump Micronaut plugin to 3.7.1 from 3.7.0
2. Run any Gradle task that involves running the tests (check, test, etc.) and they won't be executed by Gradle

### Environment Information

MacOS 12.*
JDK: 17
Micronaut plugin version 3.7.1

### Version

Plugin: 3.7.1
Micronaut: 3.8.4

**Comment by melix** [comment]
I think this is a side effect of the [fix for Gradle 8](https://github.com/micronaut-projects/micronaut-gradle-plugin/pull/640).
I just created a test project (`mn create-app wut`), updated the plugin to `3.7.1` and it works, so I guess this must be something in your build script.

My educated guess would be that you have an _eager_ configuration block for `test` _before_ the `micronaut` extension is configured, e.g:

```
test { // bad, this is eager
    // configure something
}

micronaut {
    testRuntime("junit5")
}
```

which should be:

```
tasks.named("test") { // good, this is lazy
    // configure something
}

micronaut {
    testRuntime("junit5")
}
```

If you share a reproducer I can take a closer look. Alternatively, you can explicitly configure the test framework:

```
tasks.withType(Test).configureEach { useJUnitPlatform() }
```

**Comment by adamkobor** [comment]
@melix Unfortunately I can't share the code, since it's private company project, but I can tell that:
- there is no test configuration prior the `micronaut {}` block
- it's a multi-module Gradle project
- the `useJUnitPlatform()` workaround worked for us 🎉

**Comment by melix** [comment]
Thanks for the report. Hopefully release `3.7.2` should fix your issue without having to update the build scripts.

**Comment by adamkobor** [comment]
> Thanks for the report. Hopefully release `3.7.2` should fix your issue without having to update the build scripts.

Nice to hear that, thanks for your quick fix 💪
