### ISSUE TITLE
Add a plugin to automatically add the Micronaut version catalog

### ISSUE THREAD

**Issue by melix** [micronaut-projects/micronaut-gradle-plugin#668]
### Feature description

It would be nice to have a (settings) plugin which automatically applies the Micronaut Platform (4.0.0) version catalog. That is to say, instead of the user having to write:

settings.gradle
```gradle
dependencyResolutionManagement {
    versionCatalogs {
        create("mn") { from("io.micronaut.platform:micronaut-platform:$micronautVersion") }
    }
}
```

we could simply have:

```
plugins {
     id "io.micronaut.platform.catalog"
}
```

(plugin id to be chosen)

There is one catch though: in order to load the catalog, we need `micronautVersion` to be fixed when reading the settings file. This is possible if it is defined in `gradle.properties`, but _not_ if it is defined in `build.gradle`. For most users this wouldn't be an issue, though.

**Comment by nbrugger-tgm** [comment]
is it possible to define the micronaut platform version in a `.toml` file?
