### ISSUE TITLE
Micronaut section from root gradle.build not propagated to child modules

### ISSUE THREAD

**Issue by l0co** [micronaut-projects/micronaut-gradle-plugin#67]
In `2.1.2` (works in `2.1.1`).

I have the following annotations:

```java
@Client public @interface SafeClient {}
@Singleton public @interface GraphQLService {}
```

In `2.1.1` all classes annotated with `@SafeClient` and `@GraphQLService` worked properly as `@Client` and `@Singleton`. In `2.1.2` this feature doesn't work and these beans dissapeared.

**Comment by l0co** [comment]
Just for the record, I've repeated `micronaut` section in `client:build.gradle` and this workaround works. It sems the section is not propagated two or more levels down in the submodules tree.

**Comment by graemerocher** [comment]
I can't reproduce this personally. Attached is an example 

[gradle-multi-module.zip](https://github.com/micronaut-projects/micronaut-gradle-plugin/files/5545738/gradle-multi-module.zip)

For the problem with the root you should use `apply false` to avoid applying the plugin to the root:

```groovy
plugins {
    id "io.micronaut.library" version "1.1.0" apply false
}


subprojects {
    apply plugin: "io.micronaut.library"
    micronaut {
        version "2.1.3"
        processing {
            incremental false
            annotations "io.luna.*"
        }
    }    
}

```

If you still see the problem feel free to supply an example that reproduces it.

**Comment by l0co** [comment]
What if you don't want to enforce `apply plugin: "io.micronaut.library"` for all subprojects, because some of them are `io.micronaut.application`?

Please see this example: [gradle-multi-module-1.zip](https://github.com/micronaut-projects/micronaut-gradle-plugin/files/5559429/gradle-multi-module-1.zip)

```
$ gradle clean build

FAILURE: Build failed with an exception.

* Where:
Build file '/home/lukasz/Pobrane/gradle-multi-module-1/build.gradle' line: 9

* What went wrong:
A problem occurred evaluating root project 'gradle-multi-module-1'.
> Could not find method micronaut() for arguments [build_50duhonkbe3rumr9xeam67nza$_run_closure1$_closure3@128b3396] on project ':one' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 350ms
```

**Comment by ysb33r** [comment]
That is the purpose of using `apply false`
Let's say you have `projectApp` and `projectLib`

```
plugins {
    id "io.micronaut.library" version "1.1.0" apply false
    id "io.micronaut.application" version "1.1.0" apply false
}
````

Now you have two options. 

```
subprojects {

    if(project.name == 'projectApp') {
       apply plugin: 'io.micronaut.application'
    } else {
      apply plugin: 'io.micronaut.library'
    }
}
```

Or you can go the `projectApp/build.gradle`
```
plugins {
  id 'io.micronaut.application'
}
```
and in `projectLib/build.gradle`
```
plugins {
  id 'io.micronaut.library'
}
```

HTH

**Comment by l0co** [comment]
The second version is more or less used in example project I attached and the build fails.

**Comment by ysb33r** [comment]
Aargh, I should have spotted this when writing https://github.com/micronaut-projects/micronaut-gradle-plugin/issues/67#issuecomment-729600422. 

I believe what is happening is that the `subprojects` block is evaluated before the individual `build.gradle` files in the subprojects.

There are two solutions for this - either follow my first option in https://github.com/micronaut-projects/micronaut-gradle-plugin/issues/67#issuecomment-729600422.  **OR** put your common code in `gradle/micronaut.gradle` and use `apply from: "${rootDir}/gradle/micronaut.gradle"` in the respective subprojects.

**Comment by l0co** [comment]
I have another workaround in the project which works. However, currently there's no easy way to define `micronaut` section in the root `build.gradle` for all subprojects without enforcing them to apply one of your plugins (library or application). I'm just pointing this as a flaw of current configuration.

**Comment by graemerocher** [comment]
Doubt there is anything we can do about this, that is just the way Gradle works
