### ISSUE TITLE
In Micronaut Framework 4.x allow user to define micronaut.coreVersion

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-gradle-plugin#689]
In Micronaut framework 4, a [Micronaut Release is a release of Platform and starter](https://github.com/micronaut-projects/micronaut-platform/discussions/200). 

In Micronaut versions prior to 3, [using a Snapshot](https://docs.micronaut.io/latest/guide/#usingsnapshots) meant using a core snapshot. Modules had a fixed version.  

In Micronaut 4, when a user sets, `micronaut.version`, they are setting the version of Micronaut Platform BOM. Thus, they will not be using any snapshot for core. 

Moreover, the Micronaut Gradle plugin adds [dependencies](https://github.com/micronaut-projects/micronaut-gradle-plugin/blob/master/minimal-plugin/src/main/java/io/micronaut/gradle/MicronautRuntimeDependencies.java#L29-L55) automatically to the user classpath. 

Those dependencies are from `test`, `gcp`, `aws`, `servlet`, `azure`, `oracle-cloud`, and `core`. 

It would be good if the user could override via the micronaut extension those versions. 

E.g. if you have in you `gradle.properties`,  `micronautVersion=4.0.1`. You could set: 

```groovy
micronaut {
    coreVersion = '4.0.2-SNAPSHOT'
    awsVersion = '5.2.0-SNAPSHOT'
}
```

and the Micronaut Gradle plugin will add under the hood: 

```groovy
`Implementation("io.micronaut.aws:micronaut-aws-whatever:5.2.0-SNAPSHOT`")
`Implementation("io.micronaut:micronaut-inject.java:4.0.2-SNAPSHOT`")
```

[Context of this issue](https://github.com/micronaut-projects/micronaut-platform/pull/201#issuecomment-1503073331)

**Comment by graemerocher** [comment]
Think the Maven plug-in already lets you do this
