### ISSUE TITLE
Ability to set mainClass for native Lambda

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-gradle-plugin#753]
We need an option to provide the main class (the entry point for the native image) for AWS Lambda functions which use the _Default_ application type.  

We currently set it to  [io.micronaut.function.aws.runtime.MicronautLambdaRuntime](https://github.com/micronaut-projects/micronaut-gradle-plugin/blob/master/graalvm-plugin/src/main/java/io/micronaut/gradle/graalvm/MicronautGraalPlugin.java#L90)

However, we ship now serveral main classes depending on the event they need to support. 

A user may want to set: 

- [`io.micronaut.function.aws.runtime.MicronautLambdaRuntime`](https://github.com/micronaut-projects/micronaut-aws/blob/master/function-aws-custom-runtime/src/main/java/io/micronaut/function/aws/runtime/MicronautLambdaRuntime.java)
- [`io.micronaut.function.aws.runtime.APIGatewayV2HTTPEventMicronautLambdaRuntime`](https://github.com/micronaut-projects/micronaut-aws/blob/master/function-aws-custom-runtime/src/main/java/io/micronaut/function/aws/runtime/APIGatewayV2HTTPEventMicronautLambdaRuntime.java)
- [`io.micronaut.function.aws.runtime.ApplicationLoadBalancerMicronautLambdaRuntime`](https://github.com/micronaut-projects/micronaut-aws/blob/master/function-aws-custom-runtime/src/main/java/io/micronaut/function/aws/runtime/ApplicationLoadBalancerMicronautLambdaRuntime.java)

it would be nice we could do: 

```kotlin
micronaut {
    nativeLambda {
        mainClass.set("io.micronaut.function.aws.runtime.APIGatewayV2HTTPEventMicronautLambdaRuntime")
    }
}
```

**Comment by melix** [comment]
I would rather have an extension like this:

```
micronaut {
    aws {
        nativeRuntime(AwsRuntime.Micronaut)
        // or
        nativeRuntime(AwsRuntime.ApiGateway)
        // or
        nativeRuntime(AwsRuntime.LoadBalancer)
    }
}
```

Or something along these lines. I don't know if it makes sense to have a runtime independently of native. wdyt?

**Comment by sdelamo** [comment]
@alvarosanchez we need this for the maven plugin as well.

**Comment by sdelamo** [comment]
The reason I said `nativeLambda` as the key of the extension is because you are running the gradle task `buildNativeLambda`. This is configuration to be used by that task.

Since you are setting the main Class hence the `mainClass` key instead of `nativeRuntime` which may be confusion to `runtime`which we already set correctly to `lambda_provided`.

Moreover, I would use `lambda` instead of `aws`. Since this only applies to lambda. 

but the important thing is that this is configurable.

**Comment by alvarosanchez** [comment]
> @alvarosanchez we need this for the maven plugin as well.

Please create an issue there

**Comment by Ic-ks** [comment]
Hi :) Is there a possibility to set the `mainClass` for native lambdas for micronaut versions < 4.0.0? I did a lot of debugging and thought that the the following code (`build.gradle.kts`):
```
graalvmNative{
    toolchainDetection.set(false)
    binaries {
        named("main") {
            mainClass.set("com.example.FunctionLambdaRuntime")
        }
    }
}
```
 could work. Unfortunately it does not work. The value gets overridden with the `MicronautLambdaRuntime`. The only workaround I found is overriding the `mainClass` in `NativeDockerFile.prepareNativeImageOptions()` with the debugger during the build. Is there an easier way?

**Comment by melix** [comment]
One option in 3.7.x is to use the docker file editing:

```
tasks.named('dockerfile', io.micronaut.gradle.docker.NativeImageDockerfile) {
   editDockerfile { 
       replace('RUN native-image ..-H:Class=io.micronaut.function.aws.runtime.MicronautLambdaRuntime', 'RUN native-image ....') 
   }
}
```

The issue is that you'd have to replace the whole line, which contains references to config directories and what not, so a bit fragile.

**Comment by Ic-ks** [comment]
@melix thanks for the support :) was not able to replace the line (copied it from the normal run and tried to replace it). Fortunately I found another way:
```
tasks.withType(NativeImageDockerfile::class.java).configureEach {
    nativeImageOptions.get().mainClass.set("com.example.FunctionLambdaRuntime")
}
```
