### ISSUE TITLE
delete old task nativeTest

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-gradle-plugin#768]
### Feature description

We recommend people to use `testNative` instead. It is confusing to have the other task around which is shown in the IDE.

**Comment by melix** [comment]
`testNative` doesn't exist. The task is `nativeTest.`

**Comment by melix** [comment]
`testNativeImage` was removed in b97d8fc590c47b2678d5bd0d7e2688d7c0f8c49d
