### ISSUE TITLE
Docs indicate that 4.0.0 defaults to Micronaut 4.0.0-RC1

### ISSUE THREAD

**Issue by jeffbrown** [micronaut-projects/micronaut-gradle-plugin#776]
### Issue description

The 4.0.0 docs at https://micronaut-projects.github.io/micronaut-gradle-plugin/4.0.0/ the docs include:

> This version defaults to Micronaut 4.0.0-RC1 and is tested with Gradle 8.1.1.

And a lot of the code samples reference RC1:

```
micronaut {
    version "4.0.0-RC1"
}
```

Should those be 4.0.0 instead of 4.0.0-RC1?

**Comment by melix** [comment]
This is actually true: the Gradle plugin is released _before_ Micronaut platform, so it has been tested on RC1. The next version of the plugin will use the final release.

**Comment by jeffbrown** [comment]
Thank you for the feedback.

**Comment by jeffbrown** [comment]
> As for why they show RC1, that's because that was the version which was available when the plugin was released, there wasn't any 4.0.0 release yet

Yep.  Of course that makes sense.  Thank you!

Now that 4.0.0 has been released, do you think it is sensible to show 4.0.0 in the docs instead of RC1?
