### ISSUE TITLE
Support passing JVM arguments to the AOT optimizer process

### ISSUE THREAD

**Issue by melix** [micronaut-projects/micronaut-gradle-plugin#785]
### Feature description

See https://github.com/micronaut-projects/micronaut-maven-plugin/issues/795

**Comment by melix** [comment]
This is indeed a mistake in the plugin, these methods should be public. This went unnoticed because they can be called from Groovy build scripts :facepalm:

**Comment by bysse** [comment]
Wow... Thanks for the quick fix. Now I'll just await the next release before I venture further with Loom.
