### ISSUE TITLE
dockerBuild fails for Apple silliconMac

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-gradle-plugin#794]
[Generate an app with the defaults. ](https://launch.micronaut.io)

```
./gradlew dockerBuild

> Task :dockerfile
Dockerfile written to: /Users/sdelamo/Downloads/dockertest/build/docker/main/Dockerfile

> Task :dockerBuild
Building image using context '/Users/sdelamo/Downloads/dockertest/build/docker/main'.
Using Dockerfile '/Users/sdelamo/Downloads/dockertest/build/docker/main/Dockerfile'
Using images 'demo'.
Step 1/8 : FROM openjdk:17-alpine

> Task :dockerBuild FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dockerBuild'.
> Could not build image: no matching manifest for linux/arm64/v8 in the manifest list entries

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.2.1/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 5s
6 actionable tasks: 6 executed
```

### Environment Information

Operating system: MacOS Ventura
Architecture: Apple Silicon Mac
Micronaut Gradle Plugin 4.0.2

### Version

4.0.2

**Comment by alvarosanchez** [comment]
The default base image we use [is not multi-platform](https://hub.docker.com/_/eclipse-temurin/tags?page=1&name=17-alpine).

We should change the default to `eclipse-temurin:17-jre`

**Comment by sdelamo** [comment]
The workaround would be to run `dockerfile`

copy the Dockerfile from `build/docker/main/Dockerfile` to the root of the project and replace: 

```
FROM openjdk:17-alpine
WORKDIR /home/app
COPY layers/libs /home/app/libs
COPY layers/classes /home/app/classes
COPY layers/resources /home/app/resources
COPY layers/application.jar /home/app/application.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/home/app/application.jar"]
```

with: 

```

FROM eclipse-temurin:17-jre
WORKDIR /home/app
COPY build/docker/main/layers/libs /home/app/libs
COPY build/docker/main/layers/classes /home/app/classes
COPY build/docker/main/layers/resources /home/app/resources
COPY build/docker/main/layers/application.jar /home/app/application.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/home/app/application.jar"]
```

**Comment by sdelamo** [comment]
it seems the config is: 

```

tasks.named("dockerfile") {
    from 'eclipse-temurin:17-jre'
}
```

but the generated `Dockerfile` still uses `openjdk:17-alpine`.

**Comment by alvarosanchez** [comment]
<img width="1091" alt="image" src="https://github.com/micronaut-projects/micronaut-gradle-plugin/assets/153880/8f906976-ef17-4d95-8194-a66aee1d1413">

Pretty sure this worked in Micronaut 3. Perhaps the documentation is left behind @melix ?

**Comment by melix** [comment]
mmm, we do have `baseImage` : https://github.com/micronaut-projects/micronaut-gradle-plugin/blob/1c6fba3323eabf7f543bd0fbfec89527d3a42b5a/docker-plugin/src/main/java/io/micronaut/gradle/docker/MicronautDockerfile.java#L162

but it seems that here the task type is the Docker plugin docker file, not ours :thinking:, so I think it doesn't work because you still have a `Dockerfile` at the root.

**Comment by sdelamo** [comment]
Setting the `Dockerfile` at the root as described here is the only think it works: 

https://github.com/micronaut-projects/micronaut-gradle-plugin/issues/794#issuecomment-1665351366

**Comment by melix** [comment]
There are [many problems reported with Alpine](https://betterprogramming.pub/why-i-will-never-use-alpine-linux-ever-again-a324fd0cbfd6) in any case, so changing the base image makes sense to me. I don't have the context why this was chosen in the first place.

**Comment by alvarosanchez** [comment]
Alpine became famous because it had small containers compared to that of the full distros.

But perhaps nowadays the situation is different. In fact, `17-jre` is smaller than `17-alpine`.

**Comment by sdelamo** [comment]
+1 for having a default base image with multi-platform support.

**Comment by joaquindiez** [comment]
I add this to my build.gradle.kts 

`tasks.named<io.micronaut.gradle.docker.MicronautDockerfile>("dockerfile") {
    baseImage.set( "eclipse-temurin:17-jre")
}`

and it is working in version 4.1.0

if this base image it the recomendend for multi-platform support I vote for having it as default base image

**Comment by joaquindiez** [comment]
But the above is not working when executing **optimizedDockerBuild**

`Step 1/8 : FROM openjdk:17-alpine

> Task :app:optimizedDockerBuild FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:optimizedDockerBuild'.
> Could not build image: no matching manifest for linux/arm64/v8 in the manifest list entries
`
