### ISSUE TITLE
Unable to set toolchains with io.micronaut.application

### ISSUE THREAD

**Issue by RapidTransit** [micronaut-projects/micronaut-gradle-plugin#835]
### Expected Behavior

Setting the toolchain:

```
java {    
    toolchain {
        languageVersion = JavaLanguageVersion.of(20)
    }
}
```

### Actual Behaviour

Throws an error complaining `languageVersion` can not be set, 

> A problem occurred evaluating project ':client'.
> The value for property 'languageVersion' is final and cannot be changed any further.

This is caused by a change in Gradle 8.3 behavior:

Related Issue:
https://github.com/gradle/gradle/issues/26061 

Comment of why the Change occurred:
https://github.com/gradle/gradle/issues/26061#issuecomment-1676430975

Using `io.micronaut.minimal.application` works around this issue because I believe it is caused by something related to maybe Graal being pulled in by the `io.micronaut.application` plugin. It took me a while to figure out there was a minimal plugin.

### Steps To Reproduce

1. Use Gradle 8.3 with the `io.micronaut.application` plugin
2. Try to set the toolchains `languageVersion`

### Environment Information

- OpenJDK 17 (gradle)
- OpenJDK 20 (toolchain target)
-  io.micronaut.application 4.0.3
- Gradle 8.3

### Version

4.0.3

**Comment by melix** [comment]
You can upgrade to plugin 4.1.1 to fix this

**Comment by RapidTransit** [comment]
> You can upgrade to plugin 4.1.1 to fix this

Sorry for the late reply I thought I was on the latest  version. 😅 Problem resolved.
