### ISSUE TITLE
micronaut.docker plugin is incompatibile with gradle configuration cache

### ISSUE THREAD

**Issue by Spikhalskiy** [micronaut-projects/micronaut-gradle-plugin#858]
When attempting to enable gradle configuration cache in a project with this plugin applied, the build fails with

```
  FAILURE: Build failed with an exception.
  
  * What went wrong:
  Configuration cache problems found in this build.
  
  2 problems were found storing the configuration cache.
- Task `:buildLayers` of type `io.micronaut.gradle.docker.tasks.BuildLayersTask`: cannot serialize Gradle script object references as these are not supported with the configuration cache.
  See https://docs.gradle.org/8.4/userguide/configuration_cache.html#config_cache:requirements:disallowed_types
- Task `:buildLayers` of type `io.micronaut.gradle.docker.tasks.BuildLayersTask`: invocation of 'Task.project' at execution time is unsupported.
  See https://docs.gradle.org/8.4/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution

  > Invocation of 'Task.project' by task ':buildLayers' at execution time is unsupported.
```

Gradle Configuration Cache is an experimental feature that is turned off by default, but most major plugins at this moment already support it. It would be great to see Micronaut Docker plugin supporting it too.
https://docs.gradle.org/current/userguide/configuration_cache.html

### Version

Micronaut Platform 4.1.6, Micronaut Gradle Plugins 4.1.2

**Comment by melix** [comment]
Can you share a reproducer? As far as I can tell the `BuildLayers` task doesn't use `project`, so my guess would be that some of your runtime classpath dependencies use `project` at runtime.

**Comment by Spikhalskiy** [comment]
I don't have a reproducer, this problem appears on a closed-source project that I try to make working with the gradle cache.
Can you elaborate on "some of your runtime classpath dependencies use project at runtime" a little more and what should I be looking for? It doesn't make sense to me that runtime classpath dependency would be trying / able to access a gradle `project`. Also, buildLayers is not starting an app. "execution time" in the error above is referencing a gradle plugin "execution time" as oppose to "configuration time".

**Comment by Spikhalskiy** [comment]
Thank you for your response.

The issue was caused by our own modification to buildLayers that looked the following way:

```
tasks {
    buildLayers {
        doLast {
            copy {
                from("${project.rootDir}/libs/opentelemetry-javaagent.jar")
                into(layout.buildDirectory.file("docker/main/layers/agent/"))
            }
        } 
    }
}
```
and used the project reference
