### ISSUE TITLE
prepareJitOptimimizations always seems to miss the cache

### ISSUE THREAD

**Issue by timyates** [micronaut-projects/micronaut-gradle-plugin#888]
### Steps to reproduce

```
mn create-app test
cd test
```

Add `org.gradle.caching=true` to `gradle.properties`

And then run `./gradlew clean build --scan` twice...

### Expected outcome

I would expect everything to come from the cache the second time...

### Actual outcome

The second run, cache keys are different, so we end up with 6 tasks being executed un-necessarially

https://scans.gradle.com/s/e52jt7tujjsem/timeline?cacheability=cacheable&outcome=success

**Comment by melix** [comment]
The issue comes from the properties file which contains a timestamp. Working on a fix.
