### ISSUE TITLE
clientId not set on generated class

### ISSUE THREAD

**Issue by KangoV** [micronaut-projects/micronaut-gradle-plugin#949]
### Expected Behavior

given 
```
micronaut {
    openapi {
        version = "6.6.2"
        client(file("src/main/resources/taizo-feedsmanager-v1-openapi.yaml")) {
            ...
            clientId = "my-client"
        }
    }
}
```
I would expect the API class to have:
```
@Client("my-client")
public interface MyApi {
  ...
```

### Actual Behaviour

The API class has:
```
@Client("${openapi-micronaut-client-base-path}")
public interface MyApi {
  ...
```

### Steps To Reproduce

Create or use an exiting opanapi file.
Configure gradle:
```
micronaut {
    openapi {
        version = "6.6.2"
        client(file("src/main/resources/myapi-v1-openapi.yaml")) {
            apiPackageName = "myapi.client.models"
            modelPackageName = "myapi.client.api"
            useOptional = true
            useReactive = false
            clientId = "my-client"
        }
    }
}
```
Run `./gradlew generateClientOpenApiApis`

### Environment Information

MacOS
java 21-tem
Micronaut 4.3.1
Micronaut Gradle Plugin 4.3.3

### Version

4.3.1

**Comment by KangoV** [comment]
This makes it impossible to include two generated clients in the same application.

**Comment by melix** [comment]
@altro3 can you take a look at this one? I didn't check but could be a bug in `micronaut-openapi` instead.

**Comment by altro3** [comment]
On weekend

**Comment by altro3** [comment]
@KangoV fixed. Use latest version of micronaut-openapi `6.6.3`

**Comment by KangoV** [comment]
Awesome. That worked. 

Question though, I have two clients, but they both have `path = "${openapi-micronaut-client-base-path}"`, how are they supposed to work? How do I set a different base path for each? 

Should the base path be added to the openapi configuration alongside the clientId?

**Comment by altro3** [comment]
@KangoV I don't know the answer to this question, because I didn't make the original template. I do not exclude that this is a flaw.

The problem is, I don't quite understand why it was done this way, and because of this, I can't just take the current template and redo it. I want to say, perhaps this was done for some reason and it’s not a bug at all, but “it’s the way it should be.”

Therefore, guys, please help me correctly interpret the current template and, if necessary, then formulate how best to fix it.

@melix @timyates @graemerocher @andriy-dmytruk

**Comment by altro3** [comment]
@KangoV So I studied this code, I think I made the generation more convenient. PR here: https://github.com/micronaut-projects/micronaut-openapi/pull/1467

 - Add ability to disable generating path attribute in Client annotation
 - Changed basePathSeparator default value to . symbol
 - Add suffixes by class-name or clientId to client base path placeholders

**Comment by KangoV** [comment]
That sounds exactly what I need. Thanks for this 👍 .
