### ISSUE TITLE
Allow adding additional docker commands

### ISSUE THREAD

**Issue by osh-onstructive** [micronaut-projects/micronaut-gradle-plugin#98]
Currently, I don't see a way to be able to insert additional commands to add to the generated Dockerfile, for example

```
HEALTHCHECK CMD curl -s localhost:8090/health | grep '"status":"UP"'
```

What would be nice, is to have something similar to the 'args' in the dockerfile{} configuration, where additional commands can be configured, which are inserted after the "FROM"

**Comment by graemerocher** [comment]
Had to revert the change as it caused a regression. See #116

**Comment by osh-onstructive** [comment]
A new PR has been raised which should allow this functionality to be re-introduced.
